#include "seed_imaging_cpp_pkg/user_headers/jetson_scan_src.hpp"

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

jetson_scan::jetson_scan() : jetson_scan_base()
{
    // Invoke initialize entry point
    initialize();

    LOG_INFO("jetson_scan infrastructure set up");
}

int main(int argc, char **argv)
{
    rclcpp::init(argc, argv);
    auto executor = rclcpp::executors::MultiThreadedExecutor();
    auto node = std::make_shared<jetson_scan>();
    executor.add_node(node);
    executor.spin();
    rclcpp::shutdown();
    return 0;
}
