#include "seed_imaging_cpp_pkg/base_headers/jetson_scan_base_src.hpp"

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

jetson_scan_base::jetson_scan_base() : Node("jetson_scan")
{
    cb_group_ = this->create_callback_group(rclcpp::CallbackGroupType::Reentrant);
    subscription_options_.callback_group = cb_group_;

    // Setting up connections
    jetson_scan_start_subscription_ = this->create_subscription<std_msgs::msg::Int32>(
        "/scan/start",
        1,
        std::bind(&jetson_scan_base::handle_start, this, std::placeholders::_1), subscription_options_);

    jetson_scan_zPos_subscription_ = this->create_subscription<std_msgs::msg::Int32>(
        "/stepper/z/pos",
        1,
        std::bind(&jetson_scan_base::handle_zPos, this, std::placeholders::_1), subscription_options_);

    jetson_scan_xPos_subscription_ = this->create_subscription<std_msgs::msg::Int32>(
        "/stepper/x/pos",
        1,
        std::bind(&jetson_scan_base::handle_xPos, this, std::placeholders::_1), subscription_options_);

    jetson_scan_yPos_subscription_ = this->create_subscription<std_msgs::msg::Int32>(
        "/stepper/y/pos",
        1,
        std::bind(&jetson_scan_base::handle_yPos, this, std::placeholders::_1), subscription_options_);

    jetson_scan_zCmd_publisher_ = this->create_publisher<std_msgs::msg::Int32>(
        "/stepper/z/cmd",
        1);

    jetson_scan_xCmd_publisher_ = this->create_publisher<std_msgs::msg::Int32>(
        "/stepper/x/cmd",
        1);

    jetson_scan_yCmd_publisher_ = this->create_publisher<std_msgs::msg::Int32>(
        "/stepper/y/cmd",
        1);

}

//=================================================
//  C o m m u n i c a t i o n
//=================================================

void jetson_scan_base::put_zCmd(std_msgs::msg::Int32 msg)
{
    jetson_scan_zCmd_publisher_->publish(msg);
}

void jetson_scan_base::put_xCmd(std_msgs::msg::Int32 msg)
{
    jetson_scan_xCmd_publisher_->publish(msg);
}

void jetson_scan_base::put_yCmd(std_msgs::msg::Int32 msg)
{
    jetson_scan_yCmd_publisher_->publish(msg);
}

