#ifndef ESP32_STEPPER_BASE_H
#define ESP32_STEPPER_BASE_H

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

#include <stdio.h>
#include <rcl/rcl.h>
#include <rclc/rclc.h>
#include <rclc/executor.h>
#include <rcutils/logging_macros.h>
#include "std_msgs/msg/int32.h"

#include "seed_imaging_microros_pkg/base_headers/example_types.h"

// Logger name used by the LOG_* macros.  It defaults to the node name and is
// updated to the node's actual logger name (rcl_node_get_logger_name) during
// esp32_stepper_base_init.
extern const char * esp32_stepper_logger_name;

#define LOG_INFO(fmt, ...) RCUTILS_LOG_INFO_NAMED(esp32_stepper_logger_name, fmt, ##__VA_ARGS__)
#define LOG_WARN(fmt, ...) RCUTILS_LOG_WARN_NAMED(esp32_stepper_logger_name, fmt, ##__VA_ARGS__)
#define LOG_ERROR(fmt, ...) RCUTILS_LOG_ERROR_NAMED(esp32_stepper_logger_name, fmt, ##__VA_ARGS__)

// rcl/rclc report entity-creation failures by return code rather than by trapping,
// and on an MCU the usual causes -- an exhausted RMW_UXRCE_MAX_* pool, an
// unreachable agent -- are exactly the ones worth seeing.  Running on past one
// leaves a node that spins normally but silently never publishes or receives, so
// esp32_stepper_base_init stops at the first failure and hands the status back.
// Expands to a return, so it is usable only in a function returning rcl_ret_t.
#define RCL_CHECK(fn) do { rcl_ret_t rc_ = (fn); if (rc_ != RCL_RET_OK) { LOG_ERROR("rcl call failed at %s:%d with status %d", __FILE__, __LINE__, (int) rc_); return rc_; } } while (0)


//=================================================
//  N o d e   S t a t e
//=================================================

typedef struct {
    rcl_node_t node;
    rclc_support_t support;
    rcl_allocator_t allocator;

    //=================================================
    //  C o m m u n i c a t i o n
    //=================================================
    rcl_publisher_t esp32_stepper_zPos_publisher;
    // zPos: the copy is required -- put_zPos is handed a pointer to a
    // local in the entry point, and sendOutputs runs after that frame is gone
    std_msgs__msg__Int32 esp32_stepper_zPos_out;
    bool esp32_stepper_zPos_out_hasValue;
    rcl_publisher_t esp32_stepper_xPos_publisher;
    // xPos: the copy is required -- put_xPos is handed a pointer to a
    // local in the entry point, and sendOutputs runs after that frame is gone
    std_msgs__msg__Int32 esp32_stepper_xPos_out;
    bool esp32_stepper_xPos_out_hasValue;
    rcl_publisher_t esp32_stepper_yPos_publisher;
    // yPos: the copy is required -- put_yPos is handed a pointer to a
    // local in the entry point, and sendOutputs runs after that frame is gone
    std_msgs__msg__Int32 esp32_stepper_yPos_out;
    bool esp32_stepper_yPos_out_hasValue;

    //=================================================
    //  S u b s c r i p t i o n s
    //=================================================
    rcl_subscription_t esp32_stepper_zCmd_subscription;
    std_msgs__msg__Int32 esp32_stepper_zCmd_msg;
    rcl_subscription_t esp32_stepper_xCmd_subscription;
    std_msgs__msg__Int32 esp32_stepper_xCmd_msg;
    rcl_subscription_t esp32_stepper_yCmd_subscription;
    std_msgs__msg__Int32 esp32_stepper_yCmd_msg;

    //=================================================
    //  E x e c u t o r
    //=================================================
    rclc_executor_t executor;
} esp32_stepper_base_t;

// Returns RCL_RET_OK, or the status of the first rcl/rclc call that failed.
rcl_ret_t esp32_stepper_base_init(esp32_stepper_base_t * self);
void esp32_stepper_base_spin(esp32_stepper_base_t * self);

//=================================================
//  C o m m u n i c a t i o n
//=================================================

void put_zPos(esp32_stepper_base_t * self, std_msgs__msg__Int32 * msg);
void put_xPos(esp32_stepper_base_t * self, std_msgs__msg__Int32 * msg);
void put_yPos(esp32_stepper_base_t * self, std_msgs__msg__Int32 * msg);

#endif  // ESP32_STEPPER_BASE_H
