// #Sireum

package seedimaging.SeedImaging

import org.sireum._
import seedimaging._
import seedimaging.GumboXUtil.GumboXResult

// Do not edit this file as it will be overwritten if HAMR codegen is rerun
@msig trait ScanController_jetson_scan_GumboX_TestHarness extends ScanController_jetson_scan_TestApi {
  def verbose: B

  /** Contract-based test harness for the initialise entry point
    */
  def testInitialiseCB(
      ): GumboXResult.Type = {

    if (verbose) {
      println(st"""Pre State Values:
                  """.render)
    }

    // [InvokeEntryPoint]: invoke the entry point test method
    testInitialise()

    // [RetrieveOutState]: retrieve values of the output ports via get operations and GUMBO declared local state variable
    val api_xCmd: Option[std_msgs.Int32] = get_xCmd()
    val api_yCmd: Option[std_msgs.Int32] = get_yCmd()
    val api_zCmd: Option[std_msgs.Int32] = get_zCmd()
    val pending: Base_Types.Boolean = seedimaging.SeedImaging.ScanController_jetson_scan.pending
    val awaitAxis: Base_Types.Integer_32 = seedimaging.SeedImaging.ScanController_jetson_scan.awaitAxis
    val tiltEstimate: Base_Types.Integer_32 = seedimaging.SeedImaging.ScanController_jetson_scan.tiltEstimate
    val planIndex: Base_Types.Integer_32 = seedimaging.SeedImaging.ScanController_jetson_scan.planIndex
    val planEnd: Base_Types.Integer_32 = seedimaging.SeedImaging.ScanController_jetson_scan.planEnd
    val halted: Base_Types.Boolean = seedimaging.SeedImaging.ScanController_jetson_scan.halted

    if (verbose) {
      println(st"""Post State Values:
                  |  api_xCmd = ${api_xCmd.string}
                  |  api_yCmd = ${api_yCmd.string}
                  |  api_zCmd = ${api_zCmd.string}
                  |  pending = ${pending.string}
                  |  awaitAxis = ${awaitAxis.string}
                  |  tiltEstimate = ${tiltEstimate.string}
                  |  planIndex = ${planIndex.string}
                  |  planEnd = ${planEnd.string}
                  |  halted = ${halted.string}""".render)
    }

    // [CheckPost]: invoke the oracle function
    val postResult = seedimaging.SeedImaging.ScanController_jetson_scan_GumboX.inititialize_IEP_Post(awaitAxis, halted, pending, planEnd, planIndex, tiltEstimate, api_xCmd, api_yCmd, api_zCmd)
    val result: GumboXResult.Type =
      if (!postResult) GumboXResult.Post_Condition_Fail
      else GumboXResult.Post_Condition_Pass

    return result
  }

  def testComputeCBJ(json: String): GumboXResult.Type = {
    seedimaging.JSON.toSeedImagingScanController_jetson_scan_PreState_Container(json) match {
      case Either.Left(o) => return testComputeCBV(o)
      case Either.Right(msg) => halt(msg.string)
    }
  }

  def testComputeCBV(o: ScanController_jetson_scan_PreState_Container): GumboXResult.Type = {
    return testComputeCB(o.api_start, o.api_xPos, o.api_yPos, o.api_zPos)
  }

  /** Contract-based test harness for the compute entry point
    * @param api_start incoming event data port
    * @param api_xPos incoming event data port
    * @param api_yPos incoming event data port
    * @param api_zPos incoming event data port
    */
  def testComputeCB(
      api_start: Option[std_msgs.Int32],
      api_xPos: Option[std_msgs.Int32],
      api_yPos: Option[std_msgs.Int32],
      api_zPos: Option[std_msgs.Int32]): GumboXResult.Type = {

    // [SaveInLocal]: retrieve and save the current (input) values of GUMBO-declared local state variables as retrieved from the component state
    val In_pending: Base_Types.Boolean = seedimaging.SeedImaging.ScanController_jetson_scan.pending
    val In_awaitAxis: Base_Types.Integer_32 = seedimaging.SeedImaging.ScanController_jetson_scan.awaitAxis
    val In_tiltEstimate: Base_Types.Integer_32 = seedimaging.SeedImaging.ScanController_jetson_scan.tiltEstimate
    val In_planIndex: Base_Types.Integer_32 = seedimaging.SeedImaging.ScanController_jetson_scan.planIndex
    val In_planEnd: Base_Types.Integer_32 = seedimaging.SeedImaging.ScanController_jetson_scan.planEnd
    val In_halted: Base_Types.Boolean = seedimaging.SeedImaging.ScanController_jetson_scan.halted

    // [CheckPre]: check/filter based on pre-condition.
    val CEP_Pre_Result: B = seedimaging.SeedImaging.ScanController_jetson_scan_GumboX.compute_CEP_Pre (In_awaitAxis, In_halted, In_pending, In_planEnd, In_planIndex, In_tiltEstimate, api_start, api_xPos, api_yPos, api_zPos)
    if (!CEP_Pre_Result) {
      return GumboXResult.Pre_Condition_Unsat
    }

    // [PutInPorts]: put values on the input ports
    if (api_start.nonEmpty) {
      put_start(api_start.get)
    }
    if (api_xPos.nonEmpty) {
      put_xPos(api_xPos.get)
    }
    if (api_yPos.nonEmpty) {
      put_yPos(api_yPos.get)
    }
    if (api_zPos.nonEmpty) {
      put_zPos(api_zPos.get)
    }

    if (verbose) {
      println(st"""Pre State Values:
                  |  In_awaitAxis = ${In_awaitAxis.string}
                  |  In_halted = ${In_halted.string}
                  |  In_pending = ${In_pending.string}
                  |  In_planEnd = ${In_planEnd.string}
                  |  In_planIndex = ${In_planIndex.string}
                  |  In_tiltEstimate = ${In_tiltEstimate.string}
                  |  api_start = ${api_start.string}
                  |  api_xPos = ${api_xPos.string}
                  |  api_yPos = ${api_yPos.string}
                  |  api_zPos = ${api_zPos.string}""".render)
    }

    // [InvokeEntryPoint]: invoke the entry point test method
    testCompute()

    // [RetrieveOutState]: retrieve values of the output ports via get operations and GUMBO declared local state variable
    val api_xCmd: Option[std_msgs.Int32] = get_xCmd()
    val api_yCmd: Option[std_msgs.Int32] = get_yCmd()
    val api_zCmd: Option[std_msgs.Int32] = get_zCmd()
    val pending: Base_Types.Boolean = seedimaging.SeedImaging.ScanController_jetson_scan.pending
    val awaitAxis: Base_Types.Integer_32 = seedimaging.SeedImaging.ScanController_jetson_scan.awaitAxis
    val tiltEstimate: Base_Types.Integer_32 = seedimaging.SeedImaging.ScanController_jetson_scan.tiltEstimate
    val planIndex: Base_Types.Integer_32 = seedimaging.SeedImaging.ScanController_jetson_scan.planIndex
    val planEnd: Base_Types.Integer_32 = seedimaging.SeedImaging.ScanController_jetson_scan.planEnd
    val halted: Base_Types.Boolean = seedimaging.SeedImaging.ScanController_jetson_scan.halted

    if (verbose) {
      println(st"""Post State Values:
                  |  api_xCmd = ${api_xCmd.string}
                  |  api_yCmd = ${api_yCmd.string}
                  |  api_zCmd = ${api_zCmd.string}
                  |  pending = ${pending.string}
                  |  awaitAxis = ${awaitAxis.string}
                  |  tiltEstimate = ${tiltEstimate.string}
                  |  planIndex = ${planIndex.string}
                  |  planEnd = ${planEnd.string}
                  |  halted = ${halted.string}""".render)
    }

    // [CheckPost]: invoke the oracle function
    val postResult = seedimaging.SeedImaging.ScanController_jetson_scan_GumboX.compute_CEP_Post(In_awaitAxis, In_halted, In_pending, In_planEnd, In_planIndex, In_tiltEstimate, awaitAxis, halted, pending, planEnd, planIndex, tiltEstimate, api_start, api_xPos, api_yPos, api_zPos, api_xCmd, api_yCmd, api_zCmd)
    val result: GumboXResult.Type =
      if (!postResult) GumboXResult.Post_Condition_Fail
      else GumboXResult.Post_Condition_Pass

    return result
  }

  def testComputeCBwLJ(json: String): GumboXResult.Type = {
    seedimaging.JSON.toSeedImagingScanController_jetson_scan_PreState_Container_PS(json) match {
      case Either.Left(o) => return testComputeCBwLV(o)
      case Either.Right(msg) => halt(msg.string)
    }
  }

  def testComputeCBwLV(o: ScanController_jetson_scan_PreState_Container_PS): GumboXResult.Type = {
    return testComputeCBwL(o.In_awaitAxis, o.In_halted, o.In_pending, o.In_planEnd, o.In_planIndex, o.In_tiltEstimate, o.api_start, o.api_xPos, o.api_yPos, o.api_zPos)
  }

  /** Contract-based test harness for the compute entry point
    * @param In_awaitAxis pre-state state variable
    * @param In_halted pre-state state variable
    * @param In_pending pre-state state variable
    * @param In_planEnd pre-state state variable
    * @param In_planIndex pre-state state variable
    * @param In_tiltEstimate pre-state state variable
    * @param api_start incoming event data port
    * @param api_xPos incoming event data port
    * @param api_yPos incoming event data port
    * @param api_zPos incoming event data port
    */
  def testComputeCBwL(
      In_awaitAxis: Base_Types.Integer_32,
      In_halted: Base_Types.Boolean,
      In_pending: Base_Types.Boolean,
      In_planEnd: Base_Types.Integer_32,
      In_planIndex: Base_Types.Integer_32,
      In_tiltEstimate: Base_Types.Integer_32,
      api_start: Option[std_msgs.Int32],
      api_xPos: Option[std_msgs.Int32],
      api_yPos: Option[std_msgs.Int32],
      api_zPos: Option[std_msgs.Int32]): GumboXResult.Type = {

    // [CheckPre]: check/filter based on pre-condition.
    val CEP_Pre_Result: B = seedimaging.SeedImaging.ScanController_jetson_scan_GumboX.compute_CEP_Pre (In_awaitAxis, In_halted, In_pending, In_planEnd, In_planIndex, In_tiltEstimate, api_start, api_xPos, api_yPos, api_zPos)
    if (!CEP_Pre_Result) {
      return GumboXResult.Pre_Condition_Unsat
    }

    // [PutInPorts]: put values on the input ports
    if (api_start.nonEmpty) {
      put_start(api_start.get)
    }
    if (api_xPos.nonEmpty) {
      put_xPos(api_xPos.get)
    }
    if (api_yPos.nonEmpty) {
      put_yPos(api_yPos.get)
    }
    if (api_zPos.nonEmpty) {
      put_zPos(api_zPos.get)
    }

    // [SetInStateVars]: set the pre-state values of state variables
    seedimaging.SeedImaging.ScanController_jetson_scan.pending = In_pending
    seedimaging.SeedImaging.ScanController_jetson_scan.awaitAxis = In_awaitAxis
    seedimaging.SeedImaging.ScanController_jetson_scan.tiltEstimate = In_tiltEstimate
    seedimaging.SeedImaging.ScanController_jetson_scan.planIndex = In_planIndex
    seedimaging.SeedImaging.ScanController_jetson_scan.planEnd = In_planEnd
    seedimaging.SeedImaging.ScanController_jetson_scan.halted = In_halted

    if (verbose) {
      println(st"""Pre State Values:
                  |  In_awaitAxis = ${In_awaitAxis.string}
                  |  In_halted = ${In_halted.string}
                  |  In_pending = ${In_pending.string}
                  |  In_planEnd = ${In_planEnd.string}
                  |  In_planIndex = ${In_planIndex.string}
                  |  In_tiltEstimate = ${In_tiltEstimate.string}
                  |  api_start = ${api_start.string}
                  |  api_xPos = ${api_xPos.string}
                  |  api_yPos = ${api_yPos.string}
                  |  api_zPos = ${api_zPos.string}""".render)
    }

    // [InvokeEntryPoint]: invoke the entry point test method
    testCompute()

    // [RetrieveOutState]: retrieve values of the output ports via get operations and GUMBO declared local state variable
    val api_xCmd: Option[std_msgs.Int32] = get_xCmd()
    val api_yCmd: Option[std_msgs.Int32] = get_yCmd()
    val api_zCmd: Option[std_msgs.Int32] = get_zCmd()
    val pending: Base_Types.Boolean = seedimaging.SeedImaging.ScanController_jetson_scan.pending
    val awaitAxis: Base_Types.Integer_32 = seedimaging.SeedImaging.ScanController_jetson_scan.awaitAxis
    val tiltEstimate: Base_Types.Integer_32 = seedimaging.SeedImaging.ScanController_jetson_scan.tiltEstimate
    val planIndex: Base_Types.Integer_32 = seedimaging.SeedImaging.ScanController_jetson_scan.planIndex
    val planEnd: Base_Types.Integer_32 = seedimaging.SeedImaging.ScanController_jetson_scan.planEnd
    val halted: Base_Types.Boolean = seedimaging.SeedImaging.ScanController_jetson_scan.halted

    if (verbose) {
      println(st"""Post State Values:
                  |  api_xCmd = ${api_xCmd.string}
                  |  api_yCmd = ${api_yCmd.string}
                  |  api_zCmd = ${api_zCmd.string}
                  |  pending = ${pending.string}
                  |  awaitAxis = ${awaitAxis.string}
                  |  tiltEstimate = ${tiltEstimate.string}
                  |  planIndex = ${planIndex.string}
                  |  planEnd = ${planEnd.string}
                  |  halted = ${halted.string}""".render)
    }

    // [CheckPost]: invoke the oracle function
    val postResult = seedimaging.SeedImaging.ScanController_jetson_scan_GumboX.compute_CEP_Post(In_awaitAxis, In_halted, In_pending, In_planEnd, In_planIndex, In_tiltEstimate, awaitAxis, halted, pending, planEnd, planIndex, tiltEstimate, api_start, api_xPos, api_yPos, api_zPos, api_xCmd, api_yCmd, api_zCmd)
    val result: GumboXResult.Type =
      if (!postResult) GumboXResult.Post_Condition_Fail
      else GumboXResult.Post_Condition_Pass

    return result
  }
}
