// #Sireum

package seedimaging.SeedImaging

import org.sireum._
import seedimaging.util.Profile
import seedimaging.util.EmptyContainer
import seedimaging.RandomLib

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

// Profile for initialise entrypoint
@msig trait ScanController_jetson_scan_Profile_Trait extends Profile

@record class ScanController_jetson_scan_Profile (
  val name: String,
) extends ScanController_jetson_scan_Profile_Trait {

  override def next: EmptyContainer = {
    return EmptyContainer()
  }
}

// Profile with generators for incoming ports
@msig trait ScanController_jetson_scan_Profile_P_Trait extends Profile {
  def api_start: RandomLib // random lib for generating std_msgs.Int32
  def api_xPos: RandomLib // random lib for generating std_msgs.Int32
  def api_yPos: RandomLib // random lib for generating std_msgs.Int32
  def api_zPos: RandomLib // random lib for generating std_msgs.Int32

  def update_api_start(v: RandomLib): ScanController_jetson_scan_Profile_P_Trait
  def update_api_xPos(v: RandomLib): ScanController_jetson_scan_Profile_P_Trait
  def update_api_yPos(v: RandomLib): ScanController_jetson_scan_Profile_P_Trait
  def update_api_zPos(v: RandomLib): ScanController_jetson_scan_Profile_P_Trait
}

@record class ScanController_jetson_scan_Profile_P(
  val name: String,
  var api_start: RandomLib, // random lib for generating std_msgs.Int32
  var api_xPos: RandomLib, // random lib for generating std_msgs.Int32
  var api_yPos: RandomLib, // random lib for generating std_msgs.Int32
  var api_zPos: RandomLib // random lib for generating std_msgs.Int32
  ) extends ScanController_jetson_scan_Profile_P_Trait {

  override def next: ScanController_jetson_scan_PreState_Container_P = {
    return (ScanController_jetson_scan_PreState_Container_P (
      api_start = api_start.nextOptionstd_msgsInt32(),
      api_xPos = api_xPos.nextOptionstd_msgsInt32(),
      api_yPos = api_yPos.nextOptionstd_msgsInt32(),
      api_zPos = api_zPos.nextOptionstd_msgsInt32()))
  }

  override def update_api_start(v: RandomLib): ScanController_jetson_scan_Profile_P_Trait = {
    return this(api_start = v)
  }

  override def update_api_xPos(v: RandomLib): ScanController_jetson_scan_Profile_P_Trait = {
    return this(api_xPos = v)
  }

  override def update_api_yPos(v: RandomLib): ScanController_jetson_scan_Profile_P_Trait = {
    return this(api_yPos = v)
  }

  override def update_api_zPos(v: RandomLib): ScanController_jetson_scan_Profile_P_Trait = {
    return this(api_zPos = v)
  }
}

// Profile with generators for state variables and incoming ports
@msig trait ScanController_jetson_scan_Profile_PS_Trait extends ScanController_jetson_scan_Profile_P_Trait {
  def In_awaitAxis: RandomLib // random lib for generating Base_Types.Integer_32
  def In_halted: RandomLib // random lib for generating Base_Types.Boolean
  def In_pending: RandomLib // random lib for generating Base_Types.Boolean
  def In_planEnd: RandomLib // random lib for generating Base_Types.Integer_32
  def In_planIndex: RandomLib // random lib for generating Base_Types.Integer_32
  def In_tiltEstimate: RandomLib // random lib for generating Base_Types.Integer_32
  def api_start: RandomLib // random lib for generating std_msgs.Int32
  def api_xPos: RandomLib // random lib for generating std_msgs.Int32
  def api_yPos: RandomLib // random lib for generating std_msgs.Int32
  def api_zPos: RandomLib // random lib for generating std_msgs.Int32

  def update_In_awaitAxis(v: RandomLib): ScanController_jetson_scan_Profile_PS_Trait
  def update_In_halted(v: RandomLib): ScanController_jetson_scan_Profile_PS_Trait
  def update_In_pending(v: RandomLib): ScanController_jetson_scan_Profile_PS_Trait
  def update_In_planEnd(v: RandomLib): ScanController_jetson_scan_Profile_PS_Trait
  def update_In_planIndex(v: RandomLib): ScanController_jetson_scan_Profile_PS_Trait
  def update_In_tiltEstimate(v: RandomLib): ScanController_jetson_scan_Profile_PS_Trait
  def update_api_start(v: RandomLib): ScanController_jetson_scan_Profile_PS_Trait
  def update_api_xPos(v: RandomLib): ScanController_jetson_scan_Profile_PS_Trait
  def update_api_yPos(v: RandomLib): ScanController_jetson_scan_Profile_PS_Trait
  def update_api_zPos(v: RandomLib): ScanController_jetson_scan_Profile_PS_Trait
}

@record class ScanController_jetson_scan_Profile_PS(
  val name: String,
  var In_awaitAxis: RandomLib, // random lib for generating Base_Types.Integer_32
  var In_halted: RandomLib, // random lib for generating Base_Types.Boolean
  var In_pending: RandomLib, // random lib for generating Base_Types.Boolean
  var In_planEnd: RandomLib, // random lib for generating Base_Types.Integer_32
  var In_planIndex: RandomLib, // random lib for generating Base_Types.Integer_32
  var In_tiltEstimate: RandomLib, // random lib for generating Base_Types.Integer_32
  var api_start: RandomLib, // random lib for generating std_msgs.Int32
  var api_xPos: RandomLib, // random lib for generating std_msgs.Int32
  var api_yPos: RandomLib, // random lib for generating std_msgs.Int32
  var api_zPos: RandomLib // random lib for generating std_msgs.Int32
  ) extends ScanController_jetson_scan_Profile_PS_Trait {

  override def next: ScanController_jetson_scan_PreState_Container_PS = {
    return (ScanController_jetson_scan_PreState_Container_PS (
      In_awaitAxis = In_awaitAxis.nextS32(),
      In_halted = In_halted.nextB(),
      In_pending = In_pending.nextB(),
      In_planEnd = In_planEnd.nextS32(),
      In_planIndex = In_planIndex.nextS32(),
      In_tiltEstimate = In_tiltEstimate.nextS32(),
      api_start = api_start.nextOptionstd_msgsInt32(),
      api_xPos = api_xPos.nextOptionstd_msgsInt32(),
      api_yPos = api_yPos.nextOptionstd_msgsInt32(),
      api_zPos = api_zPos.nextOptionstd_msgsInt32()))
  }

  override def update_In_awaitAxis(v: RandomLib): ScanController_jetson_scan_Profile_PS_Trait = {
    return this(In_awaitAxis = v)
  }

  override def update_In_halted(v: RandomLib): ScanController_jetson_scan_Profile_PS_Trait = {
    return this(In_halted = v)
  }

  override def update_In_pending(v: RandomLib): ScanController_jetson_scan_Profile_PS_Trait = {
    return this(In_pending = v)
  }

  override def update_In_planEnd(v: RandomLib): ScanController_jetson_scan_Profile_PS_Trait = {
    return this(In_planEnd = v)
  }

  override def update_In_planIndex(v: RandomLib): ScanController_jetson_scan_Profile_PS_Trait = {
    return this(In_planIndex = v)
  }

  override def update_In_tiltEstimate(v: RandomLib): ScanController_jetson_scan_Profile_PS_Trait = {
    return this(In_tiltEstimate = v)
  }

  override def update_api_start(v: RandomLib): ScanController_jetson_scan_Profile_PS_Trait = {
    return this(api_start = v)
  }

  override def update_api_xPos(v: RandomLib): ScanController_jetson_scan_Profile_PS_Trait = {
    return this(api_xPos = v)
  }

  override def update_api_yPos(v: RandomLib): ScanController_jetson_scan_Profile_PS_Trait = {
    return this(api_yPos = v)
  }

  override def update_api_zPos(v: RandomLib): ScanController_jetson_scan_Profile_PS_Trait = {
    return this(api_zPos = v)
  }
}
