// #Sireum

package seedimaging.SeedImaging

import org.sireum._
import art.Art
import seedimaging._

// Do not edit this file as it will be overwritten if HAMR codegen is rerun
@msig trait ScanController_jetson_scan_TestApi {

  def BeforeEntrypoint(): Unit = {
    Art.initTest(Arch.SeedImagingSystem_Instance_jetson_scan)
  }

  def AfterEntrypoint(): Unit = {
    Art.finalizeTest(Arch.SeedImagingSystem_Instance_jetson_scan)
  }

  def testCompute(): Unit = {
    Art.manuallyClearOutput()
    Art.testCompute(Arch.SeedImagingSystem_Instance_jetson_scan)
  }

  def testInitialise(): Unit = {
    Art.manuallyClearOutput()
    Art.testInitialise(Arch.SeedImagingSystem_Instance_jetson_scan)
  }

  /** helper function to set the values of all input ports.
   * @param start payloads for event data port start.
   *   ART currently supports single element event data queues so
   *   only the last element of start will be used
   * @param zPos payloads for event data port zPos.
   *   ART currently supports single element event data queues so
   *   only the last element of zPos will be used
   * @param xPos payloads for event data port xPos.
   *   ART currently supports single element event data queues so
   *   only the last element of xPos will be used
   * @param yPos payloads for event data port yPos.
   *   ART currently supports single element event data queues so
   *   only the last element of yPos will be used
   */
  def put_concrete_inputs(start : ISZ[std_msgs.Int32],
                          zPos : ISZ[std_msgs.Int32],
                          xPos : ISZ[std_msgs.Int32],
                          yPos : ISZ[std_msgs.Int32]): Unit = {
    for(v <- start){
      put_start(v)
    }
    for(v <- zPos){
      put_zPos(v)
    }
    for(v <- xPos){
      put_xPos(v)
    }
    for(v <- yPos){
      put_yPos(v)
    }
  }


  /** helper function to check ScanController_jetson_scan's
   * output ports.  Use named arguments to check subsets of the output ports.
   * @param zCmd method that will be called with the payloads to be sent
   *        on the outgoing event data port 'zCmd'.
   * @param xCmd method that will be called with the payloads to be sent
   *        on the outgoing event data port 'xCmd'.
   * @param yCmd method that will be called with the payloads to be sent
   *        on the outgoing event data port 'yCmd'.
   */
  def check_concrete_output(zCmd: ISZ[std_msgs.Int32] => B,
                            xCmd: ISZ[std_msgs.Int32] => B,
                            yCmd: ISZ[std_msgs.Int32] => B): Unit = {
    var testFailures: ISZ[ST] = ISZ()

    var zCmdValue: ISZ[std_msgs.Int32] = ISZ()
    // TODO: event data port getter should return all of the events/payloads
    //       received on event data ports when queue sizes > 1 support is added
    //       to ART
    if(get_zCmd().nonEmpty) { zCmdValue = zCmdValue :+ get_zCmd().get }
    if(!zCmd(zCmdValue)) {
      testFailures = testFailures :+ st"'zCmd' did not match expected: received ${zCmdValue.size} events with the following payloads ${zCmdValue}"
    }
    var xCmdValue: ISZ[std_msgs.Int32] = ISZ()
    // TODO: event data port getter should return all of the events/payloads
    //       received on event data ports when queue sizes > 1 support is added
    //       to ART
    if(get_xCmd().nonEmpty) { xCmdValue = xCmdValue :+ get_xCmd().get }
    if(!xCmd(xCmdValue)) {
      testFailures = testFailures :+ st"'xCmd' did not match expected: received ${xCmdValue.size} events with the following payloads ${xCmdValue}"
    }
    var yCmdValue: ISZ[std_msgs.Int32] = ISZ()
    // TODO: event data port getter should return all of the events/payloads
    //       received on event data ports when queue sizes > 1 support is added
    //       to ART
    if(get_yCmd().nonEmpty) { yCmdValue = yCmdValue :+ get_yCmd().get }
    if(!yCmd(yCmdValue)) {
      testFailures = testFailures :+ st"'yCmd' did not match expected: received ${yCmdValue.size} events with the following payloads ${yCmdValue}"
    }

    assert(testFailures.isEmpty, st"${(testFailures, "\n")}".render)
  }


  // setter for in EventDataPort
  def put_start(value : std_msgs.Int32): Unit = {
    Art.insertInInfrastructurePort(Arch.SeedImagingSystem_Instance_jetson_scan.operational_api.start_Id, std_msgs.Int32_Payload(value))
  }

  // setter for in EventDataPort
  def put_zPos(value : std_msgs.Int32): Unit = {
    Art.insertInInfrastructurePort(Arch.SeedImagingSystem_Instance_jetson_scan.operational_api.zPos_Id, std_msgs.Int32_Payload(value))
  }

  // setter for in EventDataPort
  def put_xPos(value : std_msgs.Int32): Unit = {
    Art.insertInInfrastructurePort(Arch.SeedImagingSystem_Instance_jetson_scan.operational_api.xPos_Id, std_msgs.Int32_Payload(value))
  }

  // setter for in EventDataPort
  def put_yPos(value : std_msgs.Int32): Unit = {
    Art.insertInInfrastructurePort(Arch.SeedImagingSystem_Instance_jetson_scan.operational_api.yPos_Id, std_msgs.Int32_Payload(value))
  }

  // getter for out EventDataPort
  def get_zCmd(): Option[std_msgs.Int32] = {
    val value: Option[std_msgs.Int32] = get_zCmd_payload() match {
      case Some(std_msgs.Int32_Payload(v)) => Some(v)
      case Some(v) => halt(s"Unexpected payload on port zCmd.  Expecting 'std_msgs.Int32_Payload' but received ${v}")
      case _ => None[std_msgs.Int32]()
    }
    return value
  }

  // payload getter for out EventDataPort
  def get_zCmd_payload(): Option[std_msgs.Int32_Payload] = {
    return Art.observeOutInfrastructurePort(Arch.SeedImagingSystem_Instance_jetson_scan.initialization_api.zCmd_Id).asInstanceOf[Option[std_msgs.Int32_Payload]]
  }

  // getter for out EventDataPort
  def get_xCmd(): Option[std_msgs.Int32] = {
    val value: Option[std_msgs.Int32] = get_xCmd_payload() match {
      case Some(std_msgs.Int32_Payload(v)) => Some(v)
      case Some(v) => halt(s"Unexpected payload on port xCmd.  Expecting 'std_msgs.Int32_Payload' but received ${v}")
      case _ => None[std_msgs.Int32]()
    }
    return value
  }

  // payload getter for out EventDataPort
  def get_xCmd_payload(): Option[std_msgs.Int32_Payload] = {
    return Art.observeOutInfrastructurePort(Arch.SeedImagingSystem_Instance_jetson_scan.initialization_api.xCmd_Id).asInstanceOf[Option[std_msgs.Int32_Payload]]
  }

  // getter for out EventDataPort
  def get_yCmd(): Option[std_msgs.Int32] = {
    val value: Option[std_msgs.Int32] = get_yCmd_payload() match {
      case Some(std_msgs.Int32_Payload(v)) => Some(v)
      case Some(v) => halt(s"Unexpected payload on port yCmd.  Expecting 'std_msgs.Int32_Payload' but received ${v}")
      case _ => None[std_msgs.Int32]()
    }
    return value
  }

  // payload getter for out EventDataPort
  def get_yCmd_payload(): Option[std_msgs.Int32_Payload] = {
    return Art.observeOutInfrastructurePort(Arch.SeedImagingSystem_Instance_jetson_scan.initialization_api.yCmd_Id).asInstanceOf[Option[std_msgs.Int32_Payload]]
  }

}
