// #Sireum

package seedimaging.SeedImaging

import org.sireum._
import art.Art
import seedimaging._

// Do not edit this file as it will be overwritten if HAMR codegen is rerun
@msig trait StepperController_esp32_stepper_TestApi {

  def BeforeEntrypoint(): Unit = {
    Art.initTest(Arch.SeedImagingSystem_Instance_esp32_stepper)
  }

  def AfterEntrypoint(): Unit = {
    Art.finalizeTest(Arch.SeedImagingSystem_Instance_esp32_stepper)
  }

  def testCompute(): Unit = {
    Art.manuallyClearOutput()
    Art.testCompute(Arch.SeedImagingSystem_Instance_esp32_stepper)
  }

  def testInitialise(): Unit = {
    Art.manuallyClearOutput()
    Art.testInitialise(Arch.SeedImagingSystem_Instance_esp32_stepper)
  }

  /** helper function to set the values of all input ports.
   * @param zCmd payloads for event data port zCmd.
   *   ART currently supports single element event data queues so
   *   only the last element of zCmd will be used
   * @param xCmd payloads for event data port xCmd.
   *   ART currently supports single element event data queues so
   *   only the last element of xCmd will be used
   * @param yCmd payloads for event data port yCmd.
   *   ART currently supports single element event data queues so
   *   only the last element of yCmd will be used
   */
  def put_concrete_inputs(zCmd : ISZ[std_msgs.Int32],
                          xCmd : ISZ[std_msgs.Int32],
                          yCmd : ISZ[std_msgs.Int32]): Unit = {
    for(v <- zCmd){
      put_zCmd(v)
    }
    for(v <- xCmd){
      put_xCmd(v)
    }
    for(v <- yCmd){
      put_yCmd(v)
    }
  }


  /** helper function to check StepperController_esp32_stepper's
   * output ports.  Use named arguments to check subsets of the output ports.
   * @param zPos method that will be called with the payloads to be sent
   *        on the outgoing event data port 'zPos'.
   * @param xPos method that will be called with the payloads to be sent
   *        on the outgoing event data port 'xPos'.
   * @param yPos method that will be called with the payloads to be sent
   *        on the outgoing event data port 'yPos'.
   */
  def check_concrete_output(zPos: ISZ[std_msgs.Int32] => B,
                            xPos: ISZ[std_msgs.Int32] => B,
                            yPos: ISZ[std_msgs.Int32] => B): Unit = {
    var testFailures: ISZ[ST] = ISZ()

    var zPosValue: ISZ[std_msgs.Int32] = ISZ()
    // TODO: event data port getter should return all of the events/payloads
    //       received on event data ports when queue sizes > 1 support is added
    //       to ART
    if(get_zPos().nonEmpty) { zPosValue = zPosValue :+ get_zPos().get }
    if(!zPos(zPosValue)) {
      testFailures = testFailures :+ st"'zPos' did not match expected: received ${zPosValue.size} events with the following payloads ${zPosValue}"
    }
    var xPosValue: ISZ[std_msgs.Int32] = ISZ()
    // TODO: event data port getter should return all of the events/payloads
    //       received on event data ports when queue sizes > 1 support is added
    //       to ART
    if(get_xPos().nonEmpty) { xPosValue = xPosValue :+ get_xPos().get }
    if(!xPos(xPosValue)) {
      testFailures = testFailures :+ st"'xPos' did not match expected: received ${xPosValue.size} events with the following payloads ${xPosValue}"
    }
    var yPosValue: ISZ[std_msgs.Int32] = ISZ()
    // TODO: event data port getter should return all of the events/payloads
    //       received on event data ports when queue sizes > 1 support is added
    //       to ART
    if(get_yPos().nonEmpty) { yPosValue = yPosValue :+ get_yPos().get }
    if(!yPos(yPosValue)) {
      testFailures = testFailures :+ st"'yPos' did not match expected: received ${yPosValue.size} events with the following payloads ${yPosValue}"
    }

    assert(testFailures.isEmpty, st"${(testFailures, "\n")}".render)
  }


  // setter for in EventDataPort
  def put_zCmd(value : std_msgs.Int32): Unit = {
    Art.insertInInfrastructurePort(Arch.SeedImagingSystem_Instance_esp32_stepper.operational_api.zCmd_Id, std_msgs.Int32_Payload(value))
  }

  // setter for in EventDataPort
  def put_xCmd(value : std_msgs.Int32): Unit = {
    Art.insertInInfrastructurePort(Arch.SeedImagingSystem_Instance_esp32_stepper.operational_api.xCmd_Id, std_msgs.Int32_Payload(value))
  }

  // setter for in EventDataPort
  def put_yCmd(value : std_msgs.Int32): Unit = {
    Art.insertInInfrastructurePort(Arch.SeedImagingSystem_Instance_esp32_stepper.operational_api.yCmd_Id, std_msgs.Int32_Payload(value))
  }

  // getter for out EventDataPort
  def get_zPos(): Option[std_msgs.Int32] = {
    val value: Option[std_msgs.Int32] = get_zPos_payload() match {
      case Some(std_msgs.Int32_Payload(v)) => Some(v)
      case Some(v) => halt(s"Unexpected payload on port zPos.  Expecting 'std_msgs.Int32_Payload' but received ${v}")
      case _ => None[std_msgs.Int32]()
    }
    return value
  }

  // payload getter for out EventDataPort
  def get_zPos_payload(): Option[std_msgs.Int32_Payload] = {
    return Art.observeOutInfrastructurePort(Arch.SeedImagingSystem_Instance_esp32_stepper.initialization_api.zPos_Id).asInstanceOf[Option[std_msgs.Int32_Payload]]
  }

  // getter for out EventDataPort
  def get_xPos(): Option[std_msgs.Int32] = {
    val value: Option[std_msgs.Int32] = get_xPos_payload() match {
      case Some(std_msgs.Int32_Payload(v)) => Some(v)
      case Some(v) => halt(s"Unexpected payload on port xPos.  Expecting 'std_msgs.Int32_Payload' but received ${v}")
      case _ => None[std_msgs.Int32]()
    }
    return value
  }

  // payload getter for out EventDataPort
  def get_xPos_payload(): Option[std_msgs.Int32_Payload] = {
    return Art.observeOutInfrastructurePort(Arch.SeedImagingSystem_Instance_esp32_stepper.initialization_api.xPos_Id).asInstanceOf[Option[std_msgs.Int32_Payload]]
  }

  // getter for out EventDataPort
  def get_yPos(): Option[std_msgs.Int32] = {
    val value: Option[std_msgs.Int32] = get_yPos_payload() match {
      case Some(std_msgs.Int32_Payload(v)) => Some(v)
      case Some(v) => halt(s"Unexpected payload on port yPos.  Expecting 'std_msgs.Int32_Payload' but received ${v}")
      case _ => None[std_msgs.Int32]()
    }
    return value
  }

  // payload getter for out EventDataPort
  def get_yPos_payload(): Option[std_msgs.Int32_Payload] = {
    return Art.observeOutInfrastructurePort(Arch.SeedImagingSystem_Instance_esp32_stepper.initialization_api.yPos_Id).asInstanceOf[Option[std_msgs.Int32_Payload]]
  }

}
