// #Sireum

package seedimaging.SeedImaging

import org.sireum._
import seedimaging._
import seedimaging.GumboXUtil.GumboXResult

// Do not edit this file as it will be overwritten if HAMR codegen is rerun
@msig trait StepperController_esp32_stepper_GumboX_TestHarness extends StepperController_esp32_stepper_TestApi {
  def verbose: B

  /** Contract-based test harness for the initialise entry point
    */
  def testInitialiseCB(
      ): GumboXResult.Type = {

    if (verbose) {
      println(st"""Pre State Values:
                  """.render)
    }

    // [InvokeEntryPoint]: invoke the entry point test method
    testInitialise()

    // [RetrieveOutState]: retrieve values of the output ports via get operations and GUMBO declared local state variable
    val api_xPos: Option[std_msgs.Int32] = get_xPos()
    val api_yPos: Option[std_msgs.Int32] = get_yPos()
    val api_zPos: Option[std_msgs.Int32] = get_zPos()
    val zPosition: Base_Types.Integer_32 = seedimaging.SeedImaging.StepperController_esp32_stepper.zPosition
    val xPosition: Base_Types.Integer_32 = seedimaging.SeedImaging.StepperController_esp32_stepper.xPosition
    val yPosition: Base_Types.Integer_32 = seedimaging.SeedImaging.StepperController_esp32_stepper.yPosition

    if (verbose) {
      println(st"""Post State Values:
                  |  api_xPos = ${api_xPos.string}
                  |  api_yPos = ${api_yPos.string}
                  |  api_zPos = ${api_zPos.string}
                  |  zPosition = ${zPosition.string}
                  |  xPosition = ${xPosition.string}
                  |  yPosition = ${yPosition.string}""".render)
    }

    // [CheckPost]: invoke the oracle function
    val postResult = seedimaging.SeedImaging.StepperController_esp32_stepper_GumboX.inititialize_IEP_Post(xPosition, yPosition, zPosition, api_xPos, api_yPos, api_zPos)
    val result: GumboXResult.Type =
      if (!postResult) GumboXResult.Post_Condition_Fail
      else GumboXResult.Post_Condition_Pass

    return result
  }

  def testComputeCBJ(json: String): GumboXResult.Type = {
    seedimaging.JSON.toSeedImagingStepperController_esp32_stepper_PreState_Container(json) match {
      case Either.Left(o) => return testComputeCBV(o)
      case Either.Right(msg) => halt(msg.string)
    }
  }

  def testComputeCBV(o: StepperController_esp32_stepper_PreState_Container): GumboXResult.Type = {
    return testComputeCB(o.api_xCmd, o.api_yCmd, o.api_zCmd)
  }

  /** Contract-based test harness for the compute entry point
    * @param api_xCmd incoming event data port
    * @param api_yCmd incoming event data port
    * @param api_zCmd incoming event data port
    */
  def testComputeCB(
      api_xCmd: Option[std_msgs.Int32],
      api_yCmd: Option[std_msgs.Int32],
      api_zCmd: Option[std_msgs.Int32]): GumboXResult.Type = {

    // [SaveInLocal]: retrieve and save the current (input) values of GUMBO-declared local state variables as retrieved from the component state
    val In_zPosition: Base_Types.Integer_32 = seedimaging.SeedImaging.StepperController_esp32_stepper.zPosition
    val In_xPosition: Base_Types.Integer_32 = seedimaging.SeedImaging.StepperController_esp32_stepper.xPosition
    val In_yPosition: Base_Types.Integer_32 = seedimaging.SeedImaging.StepperController_esp32_stepper.yPosition

    // [CheckPre]: check/filter based on pre-condition.
    val CEP_Pre_Result: B = seedimaging.SeedImaging.StepperController_esp32_stepper_GumboX.compute_CEP_Pre (In_xPosition, In_yPosition, In_zPosition, api_xCmd, api_yCmd, api_zCmd)
    if (!CEP_Pre_Result) {
      return GumboXResult.Pre_Condition_Unsat
    }

    // [PutInPorts]: put values on the input ports
    if (api_xCmd.nonEmpty) {
      put_xCmd(api_xCmd.get)
    }
    if (api_yCmd.nonEmpty) {
      put_yCmd(api_yCmd.get)
    }
    if (api_zCmd.nonEmpty) {
      put_zCmd(api_zCmd.get)
    }

    if (verbose) {
      println(st"""Pre State Values:
                  |  In_xPosition = ${In_xPosition.string}
                  |  In_yPosition = ${In_yPosition.string}
                  |  In_zPosition = ${In_zPosition.string}
                  |  api_xCmd = ${api_xCmd.string}
                  |  api_yCmd = ${api_yCmd.string}
                  |  api_zCmd = ${api_zCmd.string}""".render)
    }

    // [InvokeEntryPoint]: invoke the entry point test method
    testCompute()

    // [RetrieveOutState]: retrieve values of the output ports via get operations and GUMBO declared local state variable
    val api_xPos: Option[std_msgs.Int32] = get_xPos()
    val api_yPos: Option[std_msgs.Int32] = get_yPos()
    val api_zPos: Option[std_msgs.Int32] = get_zPos()
    val zPosition: Base_Types.Integer_32 = seedimaging.SeedImaging.StepperController_esp32_stepper.zPosition
    val xPosition: Base_Types.Integer_32 = seedimaging.SeedImaging.StepperController_esp32_stepper.xPosition
    val yPosition: Base_Types.Integer_32 = seedimaging.SeedImaging.StepperController_esp32_stepper.yPosition

    if (verbose) {
      println(st"""Post State Values:
                  |  api_xPos = ${api_xPos.string}
                  |  api_yPos = ${api_yPos.string}
                  |  api_zPos = ${api_zPos.string}
                  |  zPosition = ${zPosition.string}
                  |  xPosition = ${xPosition.string}
                  |  yPosition = ${yPosition.string}""".render)
    }

    // [CheckPost]: invoke the oracle function
    val postResult = seedimaging.SeedImaging.StepperController_esp32_stepper_GumboX.compute_CEP_Post(In_xPosition, In_yPosition, In_zPosition, xPosition, yPosition, zPosition, api_xCmd, api_yCmd, api_zCmd, api_xPos, api_yPos, api_zPos)
    val result: GumboXResult.Type =
      if (!postResult) GumboXResult.Post_Condition_Fail
      else GumboXResult.Post_Condition_Pass

    return result
  }

  def testComputeCBwLJ(json: String): GumboXResult.Type = {
    seedimaging.JSON.toSeedImagingStepperController_esp32_stepper_PreState_Container_PS(json) match {
      case Either.Left(o) => return testComputeCBwLV(o)
      case Either.Right(msg) => halt(msg.string)
    }
  }

  def testComputeCBwLV(o: StepperController_esp32_stepper_PreState_Container_PS): GumboXResult.Type = {
    return testComputeCBwL(o.In_xPosition, o.In_yPosition, o.In_zPosition, o.api_xCmd, o.api_yCmd, o.api_zCmd)
  }

  /** Contract-based test harness for the compute entry point
    * @param In_xPosition pre-state state variable
    * @param In_yPosition pre-state state variable
    * @param In_zPosition pre-state state variable
    * @param api_xCmd incoming event data port
    * @param api_yCmd incoming event data port
    * @param api_zCmd incoming event data port
    */
  def testComputeCBwL(
      In_xPosition: Base_Types.Integer_32,
      In_yPosition: Base_Types.Integer_32,
      In_zPosition: Base_Types.Integer_32,
      api_xCmd: Option[std_msgs.Int32],
      api_yCmd: Option[std_msgs.Int32],
      api_zCmd: Option[std_msgs.Int32]): GumboXResult.Type = {

    // [CheckPre]: check/filter based on pre-condition.
    val CEP_Pre_Result: B = seedimaging.SeedImaging.StepperController_esp32_stepper_GumboX.compute_CEP_Pre (In_xPosition, In_yPosition, In_zPosition, api_xCmd, api_yCmd, api_zCmd)
    if (!CEP_Pre_Result) {
      return GumboXResult.Pre_Condition_Unsat
    }

    // [PutInPorts]: put values on the input ports
    if (api_xCmd.nonEmpty) {
      put_xCmd(api_xCmd.get)
    }
    if (api_yCmd.nonEmpty) {
      put_yCmd(api_yCmd.get)
    }
    if (api_zCmd.nonEmpty) {
      put_zCmd(api_zCmd.get)
    }

    // [SetInStateVars]: set the pre-state values of state variables
    seedimaging.SeedImaging.StepperController_esp32_stepper.zPosition = In_zPosition
    seedimaging.SeedImaging.StepperController_esp32_stepper.xPosition = In_xPosition
    seedimaging.SeedImaging.StepperController_esp32_stepper.yPosition = In_yPosition

    if (verbose) {
      println(st"""Pre State Values:
                  |  In_xPosition = ${In_xPosition.string}
                  |  In_yPosition = ${In_yPosition.string}
                  |  In_zPosition = ${In_zPosition.string}
                  |  api_xCmd = ${api_xCmd.string}
                  |  api_yCmd = ${api_yCmd.string}
                  |  api_zCmd = ${api_zCmd.string}""".render)
    }

    // [InvokeEntryPoint]: invoke the entry point test method
    testCompute()

    // [RetrieveOutState]: retrieve values of the output ports via get operations and GUMBO declared local state variable
    val api_xPos: Option[std_msgs.Int32] = get_xPos()
    val api_yPos: Option[std_msgs.Int32] = get_yPos()
    val api_zPos: Option[std_msgs.Int32] = get_zPos()
    val zPosition: Base_Types.Integer_32 = seedimaging.SeedImaging.StepperController_esp32_stepper.zPosition
    val xPosition: Base_Types.Integer_32 = seedimaging.SeedImaging.StepperController_esp32_stepper.xPosition
    val yPosition: Base_Types.Integer_32 = seedimaging.SeedImaging.StepperController_esp32_stepper.yPosition

    if (verbose) {
      println(st"""Post State Values:
                  |  api_xPos = ${api_xPos.string}
                  |  api_yPos = ${api_yPos.string}
                  |  api_zPos = ${api_zPos.string}
                  |  zPosition = ${zPosition.string}
                  |  xPosition = ${xPosition.string}
                  |  yPosition = ${yPosition.string}""".render)
    }

    // [CheckPost]: invoke the oracle function
    val postResult = seedimaging.SeedImaging.StepperController_esp32_stepper_GumboX.compute_CEP_Post(In_xPosition, In_yPosition, In_zPosition, xPosition, yPosition, zPosition, api_xCmd, api_yCmd, api_zCmd, api_xPos, api_yPos, api_zPos)
    val result: GumboXResult.Type =
      if (!postResult) GumboXResult.Post_Condition_Fail
      else GumboXResult.Post_Condition_Pass

    return result
  }
}
