// #Sireum

package seedimaging.SeedImaging

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

import org.sireum._
import seedimaging.GumboXUtil.GumboXResult
import seedimaging.util.{Container, Profile, UnitTestConfigurationBatch}
import seedimaging.RandomLib
import org.sireum.Random.Impl.Xoshiro256

object StepperController_esp32_stepper_UnitTestConfiguration_Util {

  def freshRandomLib: RandomLib = {
    return RandomLib(Random.Gen64Impl(Xoshiro256.create))
  }

  val tq: String = "\"\"\""

  type DefaultInitializeProfile = StepperController_esp32_stepper_Profile

  def defaultInitializeConfig: StepperController_esp32_stepper_Initialize_UnitTestConfiguration = {
    return (StepperController_esp32_stepper_Initialize_UnitTestConfiguration (
      verbose = F,
      name = "Default_Initialize_Config",
      description = "Default Initialize Configuration",
      numTests = 100,
      numTestVectorGenRetries = 100,
      failOnUnsatPreconditions = F,
      profile = StepperController_esp32_stepper_Profile (
        name = "Initialize_Default_Profile",
      ),
      genReplay = (c: Container, testName: String, r: GumboXResult.Type) => None())
    )
  }

  type DefaultComputeProfile = StepperController_esp32_stepper_Profile_P

  def defaultComputeConfig: StepperController_esp32_stepper_Compute_UnitTestConfiguration = {
    return (StepperController_esp32_stepper_Compute_UnitTestConfiguration (
      verbose = F,
      name = "Default_Compute_Config",
      description = "Default Compute Configuration",
      numTests = 100,
      numTestVectorGenRetries = 100,
      failOnUnsatPreconditions = F,
      profile = StepperController_esp32_stepper_Profile_P (
        name = "Compute_Default_Profile",
        api_xCmd = freshRandomLib,
        api_yCmd = freshRandomLib,
        api_zCmd = freshRandomLib
      ),
      genReplay = (c: Container, testName: String, r: GumboXResult.Type) => Some(
       st"""Replay Unit Test:
            |  test("Replay: $testName") {
            |    val results = seedimaging.GumboXUtil.GumboXResult.$r
            |    val json = st${tq}${seedimaging.JSON.fromutilContainer(c, T)}${tq}.render
            |    val testVector = seedimaging.JSON.toSeedImagingStepperController_esp32_stepper_PreState_Container_P(json).left
            |    assert (testComputeCBV(testVector) == results)
            |  }""".render))
    )
  }

  type DefaultComputewLProfile = StepperController_esp32_stepper_Profile_PS

  def defaultComputewLConfig: StepperController_esp32_stepper_ComputewL_UnitTestConfiguration = {
    return (StepperController_esp32_stepper_ComputewL_UnitTestConfiguration (
      verbose = F,
      name = "Default_ComputewL_Config",
      description = "Default ComputewL Configuration",
      numTests = 100,
      numTestVectorGenRetries = 100,
      failOnUnsatPreconditions = F,
      profile = StepperController_esp32_stepper_Profile_PS (
        name = "ComputewL_Default_Profile",
        In_xPosition = freshRandomLib,
        In_yPosition = freshRandomLib,
        In_zPosition = freshRandomLib,
        api_xCmd = freshRandomLib,
        api_yCmd = freshRandomLib,
        api_zCmd = freshRandomLib
      ),
      genReplay = (c: Container, testName: String, r: GumboXResult.Type) => Some(
       st"""Replay Unit Test:
            |  test("Replay: $testName") {
            |    val results = seedimaging.GumboXUtil.GumboXResult.$r
            |    val json = st${tq}${seedimaging.JSON.fromutilContainer(c, T)}${tq}.render
            |    val testVector = seedimaging.JSON.toSeedImagingStepperController_esp32_stepper_PreState_Container_PS(json).left
            |    assert (testComputeCBwLV(testVector) == results)
            |  }""".render))
    )
  }
}

@record class StepperController_esp32_stepper_Initialize_UnitTestConfiguration (
  var verbose: B,
  var name: String,
  var description: String,
  var numTests: Z,
  var numTestVectorGenRetries: Z,
  var failOnUnsatPreconditions: B,
  var profile: StepperController_esp32_stepper_Profile_Trait,
  var genReplay: (Container, String, GumboXResult.Type) => Option[String])
  extends UnitTestConfigurationBatch with StepperController_esp32_stepper_GumboX_TestHarness {

  override def test(c: Container): GumboXResult.Type = {
    return testInitialiseCB()
  }
}

@record class StepperController_esp32_stepper_Compute_UnitTestConfiguration (
  var verbose: B,
  var name: String,
  var description: String,
  var numTests: Z,
  var numTestVectorGenRetries: Z,
  var failOnUnsatPreconditions: B,
  var profile: StepperController_esp32_stepper_Profile_P_Trait,
  var genReplay: (Container, String, GumboXResult.Type) => Option[String])
  extends UnitTestConfigurationBatch with StepperController_esp32_stepper_GumboX_TestHarness {

  override def test(c: Container): GumboXResult.Type = {
    return testComputeCBV(c.asInstanceOf[StepperController_esp32_stepper_PreState_Container])
  }
}

@record class StepperController_esp32_stepper_ComputewL_UnitTestConfiguration (
  var verbose: B,
  var name: String,
  var description: String,
  var numTests: Z,
  var numTestVectorGenRetries: Z,
  var failOnUnsatPreconditions: B,
  var profile: StepperController_esp32_stepper_Profile_PS_Trait,
  var genReplay: (Container, String, GumboXResult.Type) => Option[String])
  extends UnitTestConfigurationBatch with StepperController_esp32_stepper_GumboX_TestHarness {

  override def test(c: Container): GumboXResult.Type = {
    return testComputeCBwLV(c.asInstanceOf[StepperController_esp32_stepper_PreState_Container_PS])
  }
}
