// #Sireum

package seedimaging.SeedImaging

import org.sireum._
import seedimaging.util.Profile
import seedimaging.util.EmptyContainer
import seedimaging.RandomLib

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

// Profile for initialise entrypoint
@msig trait StepperController_esp32_stepper_Profile_Trait extends Profile

@record class StepperController_esp32_stepper_Profile (
  val name: String,
) extends StepperController_esp32_stepper_Profile_Trait {

  override def next: EmptyContainer = {
    return EmptyContainer()
  }
}

// Profile with generators for incoming ports
@msig trait StepperController_esp32_stepper_Profile_P_Trait extends Profile {
  def api_xCmd: RandomLib // random lib for generating std_msgs.Int32
  def api_yCmd: RandomLib // random lib for generating std_msgs.Int32
  def api_zCmd: RandomLib // random lib for generating std_msgs.Int32

  def update_api_xCmd(v: RandomLib): StepperController_esp32_stepper_Profile_P_Trait
  def update_api_yCmd(v: RandomLib): StepperController_esp32_stepper_Profile_P_Trait
  def update_api_zCmd(v: RandomLib): StepperController_esp32_stepper_Profile_P_Trait
}

@record class StepperController_esp32_stepper_Profile_P(
  val name: String,
  var api_xCmd: RandomLib, // random lib for generating std_msgs.Int32
  var api_yCmd: RandomLib, // random lib for generating std_msgs.Int32
  var api_zCmd: RandomLib // random lib for generating std_msgs.Int32
  ) extends StepperController_esp32_stepper_Profile_P_Trait {

  override def next: StepperController_esp32_stepper_PreState_Container_P = {
    return (StepperController_esp32_stepper_PreState_Container_P (
      api_xCmd = api_xCmd.nextOptionstd_msgsInt32(),
      api_yCmd = api_yCmd.nextOptionstd_msgsInt32(),
      api_zCmd = api_zCmd.nextOptionstd_msgsInt32()))
  }

  override def update_api_xCmd(v: RandomLib): StepperController_esp32_stepper_Profile_P_Trait = {
    return this(api_xCmd = v)
  }

  override def update_api_yCmd(v: RandomLib): StepperController_esp32_stepper_Profile_P_Trait = {
    return this(api_yCmd = v)
  }

  override def update_api_zCmd(v: RandomLib): StepperController_esp32_stepper_Profile_P_Trait = {
    return this(api_zCmd = v)
  }
}

// Profile with generators for state variables and incoming ports
@msig trait StepperController_esp32_stepper_Profile_PS_Trait extends StepperController_esp32_stepper_Profile_P_Trait {
  def In_xPosition: RandomLib // random lib for generating Base_Types.Integer_32
  def In_yPosition: RandomLib // random lib for generating Base_Types.Integer_32
  def In_zPosition: RandomLib // random lib for generating Base_Types.Integer_32
  def api_xCmd: RandomLib // random lib for generating std_msgs.Int32
  def api_yCmd: RandomLib // random lib for generating std_msgs.Int32
  def api_zCmd: RandomLib // random lib for generating std_msgs.Int32

  def update_In_xPosition(v: RandomLib): StepperController_esp32_stepper_Profile_PS_Trait
  def update_In_yPosition(v: RandomLib): StepperController_esp32_stepper_Profile_PS_Trait
  def update_In_zPosition(v: RandomLib): StepperController_esp32_stepper_Profile_PS_Trait
  def update_api_xCmd(v: RandomLib): StepperController_esp32_stepper_Profile_PS_Trait
  def update_api_yCmd(v: RandomLib): StepperController_esp32_stepper_Profile_PS_Trait
  def update_api_zCmd(v: RandomLib): StepperController_esp32_stepper_Profile_PS_Trait
}

@record class StepperController_esp32_stepper_Profile_PS(
  val name: String,
  var In_xPosition: RandomLib, // random lib for generating Base_Types.Integer_32
  var In_yPosition: RandomLib, // random lib for generating Base_Types.Integer_32
  var In_zPosition: RandomLib, // random lib for generating Base_Types.Integer_32
  var api_xCmd: RandomLib, // random lib for generating std_msgs.Int32
  var api_yCmd: RandomLib, // random lib for generating std_msgs.Int32
  var api_zCmd: RandomLib // random lib for generating std_msgs.Int32
  ) extends StepperController_esp32_stepper_Profile_PS_Trait {

  override def next: StepperController_esp32_stepper_PreState_Container_PS = {
    return (StepperController_esp32_stepper_PreState_Container_PS (
      In_xPosition = In_xPosition.nextS32(),
      In_yPosition = In_yPosition.nextS32(),
      In_zPosition = In_zPosition.nextS32(),
      api_xCmd = api_xCmd.nextOptionstd_msgsInt32(),
      api_yCmd = api_yCmd.nextOptionstd_msgsInt32(),
      api_zCmd = api_zCmd.nextOptionstd_msgsInt32()))
  }

  override def update_In_xPosition(v: RandomLib): StepperController_esp32_stepper_Profile_PS_Trait = {
    return this(In_xPosition = v)
  }

  override def update_In_yPosition(v: RandomLib): StepperController_esp32_stepper_Profile_PS_Trait = {
    return this(In_yPosition = v)
  }

  override def update_In_zPosition(v: RandomLib): StepperController_esp32_stepper_Profile_PS_Trait = {
    return this(In_zPosition = v)
  }

  override def update_api_xCmd(v: RandomLib): StepperController_esp32_stepper_Profile_PS_Trait = {
    return this(api_xCmd = v)
  }

  override def update_api_yCmd(v: RandomLib): StepperController_esp32_stepper_Profile_PS_Trait = {
    return this(api_yCmd = v)
  }

  override def update_api_zCmd(v: RandomLib): StepperController_esp32_stepper_Profile_PS_Trait = {
    return this(api_zCmd = v)
  }
}
