#include "rclcpp/rclcpp.hpp"
#include "std_msgs/msg/int32.hpp"
#include <queue>
#include <sstream>

#include "seed_imaging_cpp_pkg/base_headers/example_types.hpp"

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

class jetson_scan_base : public rclcpp::Node
{
protected:
    jetson_scan_base();

    //=================================================
    //  C o m m u n i c a t i o n
    //=================================================


    #define LOG_INFO(...) RCLCPP_INFO(this->get_logger(), __VA_ARGS__)
    #define LOG_WARN(...) RCLCPP_WARN(this->get_logger(), __VA_ARGS__)
    #define LOG_ERROR(...) RCLCPP_ERROR(this->get_logger(), __VA_ARGS__)

    void put_zCmd(std_msgs::msg::Int32 msg);
    void put_xCmd(std_msgs::msg::Int32 msg);
    void put_yCmd(std_msgs::msg::Int32 msg);

private:
    rclcpp::CallbackGroup::SharedPtr cb_group_;

    // SubscriptionOptions for assigning subscriptions to the callback group
    rclcpp::SubscriptionOptions subscription_options_;


    //=================================================
    //  C o m p u t e    E n t r y    P o i n t
    //=================================================
    virtual void handle_start(const std_msgs::msg::Int32::SharedPtr msg) = 0;
    virtual void handle_zPos(const std_msgs::msg::Int32::SharedPtr msg) = 0;
    virtual void handle_xPos(const std_msgs::msg::Int32::SharedPtr msg) = 0;
    virtual void handle_yPos(const std_msgs::msg::Int32::SharedPtr msg) = 0;

    //=================================================
    //  C o m m u n i c a t i o n
    //=================================================
    rclcpp::Subscription<std_msgs::msg::Int32>::SharedPtr jetson_scan_start_subscription_;
    rclcpp::Subscription<std_msgs::msg::Int32>::SharedPtr jetson_scan_zPos_subscription_;
    rclcpp::Subscription<std_msgs::msg::Int32>::SharedPtr jetson_scan_xPos_subscription_;
    rclcpp::Subscription<std_msgs::msg::Int32>::SharedPtr jetson_scan_yPos_subscription_;

    rclcpp::Publisher<std_msgs::msg::Int32>::SharedPtr jetson_scan_zCmd_publisher_;
    rclcpp::Publisher<std_msgs::msg::Int32>::SharedPtr jetson_scan_xCmd_publisher_;
    rclcpp::Publisher<std_msgs::msg::Int32>::SharedPtr jetson_scan_yCmd_publisher_;

};
