// #Sireum

package seedimaging.std_msgs

import org.sireum._
import seedimaging._

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

object Int32 {
  def example(): std_msgs.Int32 = {
    return std_msgs.Int32(
      data = Base_Types.Integer_32_example())
  }
}

@datatype class Int32(
  val data: S32) {
}

object Int32_Payload {
  def example(): Int32_Payload = {
    return Int32_Payload(std_msgs.Int32.example())
  }
}

@datatype class Int32_Payload(value: std_msgs.Int32) extends art.DataContent
