#!/bin/bash
# Host simulation of the whole system, exactly as generated by HAMR:
#   ros2 launch ... SeedImagingSystem_Instance.launch.py  (agent udp4 + micro-ROS node + ROS 2 node)
# then runs the contract checks.  Requires MICROROS_WS (see hamr/ros2/readme.md).
set -u
set +u  # ROS setup scripts reference unset variables

HERE=$(cd "$(dirname "$0")" && pwd)
WS=$(cd "$HERE/../../hamr/ros2" && pwd)
if [ -z "${MICROROS_WS:-}" ]; then echo "set MICROROS_WS to the micro-ROS firmware workspace"; exit 2; fi
source /opt/ros/humble/setup.bash
source "$MICROROS_WS/install/setup.bash"
source "$WS/install/setup.bash"
LOG=${LOG:-/tmp/seed_imaging_e2e_launch.log}
ros2 launch seed_imaging_cpp_pkg_bringup SeedImagingSystem_Instance.launch.py > "$LOG" 2>&1 &
LAUNCH_PID=$!
sleep 4
python3 "$HERE/e2e_contract_check.py" "$@"
RC=$?
kill -INT $LAUNCH_PID 2>/dev/null; sleep 2; kill -9 $LAUNCH_PID 2>/dev/null
pkill -f esp32_stepper_exe 2>/dev/null; pkill -f jetson_scan_exe 2>/dev/null; pkill -f micro_ros_agent 2>/dev/null
echo "--- node log (excerpt) ---"
grep -E "jetson_scan|esp32_stepper" "$LOG" | sed 's/\x1b\[[0-9;]*m//g' | tail -60
exit $RC
