// #Sireum

package seedimaging.SeedImaging

import org.sireum._
import seedimaging._
import seedimaging.util.Container

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

// containers for the pre and post state values of ports and state variables

@sig trait ScanController_jetson_scan_PreState_Container extends Container {
  def api_start: Option[std_msgs.Int32]
  def api_xPos: Option[std_msgs.Int32]
  def api_yPos: Option[std_msgs.Int32]
  def api_zPos: Option[std_msgs.Int32]
}

// container for incoming ports
@datatype class ScanController_jetson_scan_PreState_Container_P (
  val api_start: Option[std_msgs.Int32],
  val api_xPos: Option[std_msgs.Int32],
  val api_yPos: Option[std_msgs.Int32],
  val api_zPos: Option[std_msgs.Int32]) extends ScanController_jetson_scan_PreState_Container

// container for incoming ports and state variables
@datatype class ScanController_jetson_scan_PreState_Container_PS (
  val In_awaitAxis: S32,
  val In_halted: B,
  val In_pending: B,
  val In_planEnd: S32,
  val In_planIndex: S32,
  val In_tiltEstimate: S32,
  val api_start: Option[std_msgs.Int32],
  val api_xPos: Option[std_msgs.Int32],
  val api_yPos: Option[std_msgs.Int32],
  val api_zPos: Option[std_msgs.Int32]) extends ScanController_jetson_scan_PreState_Container

@sig trait ScanController_jetson_scan_PostState_Container extends Container {
  def api_xCmd: Option[std_msgs.Int32]
  def api_yCmd: Option[std_msgs.Int32]
  def api_zCmd: Option[std_msgs.Int32]
}

// container for outgoing ports
@datatype class ScanController_jetson_scan_PostState_Container_P (
  val api_xCmd: Option[std_msgs.Int32],
  val api_yCmd: Option[std_msgs.Int32],
  val api_zCmd: Option[std_msgs.Int32]) extends ScanController_jetson_scan_PostState_Container

// container for outgoing ports and state variables
@datatype class ScanController_jetson_scan_PostState_Container_PS (
  val awaitAxis: S32,
  val halted: B,
  val pending: B,
  val planEnd: S32,
  val planIndex: S32,
  val tiltEstimate: S32,
  val api_xCmd: Option[std_msgs.Int32],
  val api_yCmd: Option[std_msgs.Int32],
  val api_zCmd: Option[std_msgs.Int32]) extends ScanController_jetson_scan_PostState_Container
