// #Sireum

package seedimaging.SeedImaging

import org.sireum._
import seedimaging._
import seedimaging.util.Container

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

// containers for the pre and post state values of ports and state variables

@sig trait StepperController_esp32_stepper_PreState_Container extends Container {
  def api_xCmd: Option[std_msgs.Int32]
  def api_yCmd: Option[std_msgs.Int32]
  def api_zCmd: Option[std_msgs.Int32]
}

// container for incoming ports
@datatype class StepperController_esp32_stepper_PreState_Container_P (
  val api_xCmd: Option[std_msgs.Int32],
  val api_yCmd: Option[std_msgs.Int32],
  val api_zCmd: Option[std_msgs.Int32]) extends StepperController_esp32_stepper_PreState_Container

// container for incoming ports and state variables
@datatype class StepperController_esp32_stepper_PreState_Container_PS (
  val In_xPosition: S32,
  val In_yPosition: S32,
  val In_zPosition: S32,
  val api_xCmd: Option[std_msgs.Int32],
  val api_yCmd: Option[std_msgs.Int32],
  val api_zCmd: Option[std_msgs.Int32]) extends StepperController_esp32_stepper_PreState_Container

@sig trait StepperController_esp32_stepper_PostState_Container extends Container {
  def api_xPos: Option[std_msgs.Int32]
  def api_yPos: Option[std_msgs.Int32]
  def api_zPos: Option[std_msgs.Int32]
}

// container for outgoing ports
@datatype class StepperController_esp32_stepper_PostState_Container_P (
  val api_xPos: Option[std_msgs.Int32],
  val api_yPos: Option[std_msgs.Int32],
  val api_zPos: Option[std_msgs.Int32]) extends StepperController_esp32_stepper_PostState_Container

// container for outgoing ports and state variables
@datatype class StepperController_esp32_stepper_PostState_Container_PS (
  val xPosition: S32,
  val yPosition: S32,
  val zPosition: S32,
  val api_xPos: Option[std_msgs.Int32],
  val api_yPos: Option[std_msgs.Int32],
  val api_zPos: Option[std_msgs.Int32]) extends StepperController_esp32_stepper_PostState_Container
