// #Sireum

package seedimaging.SeedImaging

import org.sireum._
import seedimaging._
import org.sireum.S32._
import org.sireum.S32._
import org.sireum.S32._
import org.sireum.S32._
import org.sireum.S32._
import org.sireum.S32._
import org.sireum.S32._

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

object GUMBO__Library {
  @strictpure def STEPS_PER_REV(): Base_Types.Integer_32 = s32"200"

  @strictpure def MAX_MOVE_STEPS(): Base_Types.Integer_32 = s32"400"

  @strictpure def TILT_LIMIT_STEPS(): Base_Types.Integer_32 = s32"25"

  @strictpure def MAX_SCAN_MOVES(): Base_Types.Integer_32 = s32"1000"

  @strictpure def STEP_INTERVAL_MS(): Base_Types.Integer_32 = s32"5"

  @strictpure def SETTLE_MS(): Base_Types.Integer_32 = s32"80"

  @strictpure def MAX_MOVE_TIME_MS(): Base_Types.Integer_32 = MAX_MOVE_STEPS() * STEP_INTERVAL_MS() + SETTLE_MS()

  @strictpure def isBoundedMove(steps: Base_Types.Integer_32): Base_Types.Boolean = -(MAX_MOVE_STEPS()) <= steps &
    steps <= MAX_MOVE_STEPS()

  @strictpure def isTiltSafe(pos: Base_Types.Integer_32): Base_Types.Boolean = -(TILT_LIMIT_STEPS()) <= pos &
    pos <= TILT_LIMIT_STEPS()

  @strictpure def isRotaryIndex(pos: Base_Types.Integer_32): Base_Types.Boolean = s32"0" <= pos &
    pos < STEPS_PER_REV()

  @strictpure def wrapRotary(pos: Base_Types.Integer_32): Base_Types.Integer_32 = (pos % STEPS_PER_REV() + STEPS_PER_REV()) % STEPS_PER_REV()

  @strictpure def isSafeTiltMove(tilt: Base_Types.Integer_32, steps: Base_Types.Integer_32): Base_Types.Boolean = isBoundedMove(steps) && isTiltSafe(tilt) &&
    isTiltSafe(tilt + steps)
}
