#ifndef ESP32_STEPPER_SRC_H
#define ESP32_STEPPER_SRC_H

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

#include "seed_imaging_microros_pkg/base_headers/esp32_stepper_base_src.h"

//=================================================
//  I n i t i a l i z e    E n t r y    P o i n t
//=================================================
void esp32_stepper_initialize(esp32_stepper_base_t * self);

//=================================================
//  C o m p u t e    E n t r y    P o i n t
//=================================================
void esp32_stepper_handle_zCmd(esp32_stepper_base_t * self, const std_msgs__msg__Int32 * msg);
void esp32_stepper_handle_xCmd(esp32_stepper_base_t * self, const std_msgs__msg__Int32 * msg);
void esp32_stepper_handle_yCmd(esp32_stepper_base_t * self, const std_msgs__msg__Int32 * msg);

#endif  // ESP32_STEPPER_SRC_H
