// GENERATED by bin/gen_model_constants.py from sysmlv2/SeedImaging.sysml -- do not edit.
// The numeric constants of the model's GUMBO library, for the C / C++ implementation.
#ifndef SI_MODEL_CONSTANTS_H
#define SI_MODEL_CONSTANTS_H

#define SI_STEPS_PER_REV      200
#define SI_MAX_MOVE_STEPS     400
#define SI_TILT_LIMIT_STEPS   25
#define SI_MAX_SCAN_MOVES     1000
#define SI_STEP_INTERVAL_MS   5
#define SI_SETTLE_MS          80

#endif  // SI_MODEL_CONSTANTS_H
