# Hand-written (not generated by HAMR): brings up the system on the real hardware.
#
#   * micro-ROS agent on the USB serial link to the Arduino Nano ESP32
#     (the ESP32 runs the HAMR-generated StepperController, flashed from firmware/)
#   * the ROS 2 half generated by HAMR: SeedImagingSystem_Instance_ros2.launch.py
#
#   ros2 launch seed_imaging_cpp_pkg_bringup seed_imaging_hardware.launch.py
#   ros2 launch seed_imaging_cpp_pkg_bringup seed_imaging_hardware.launch.py dev:=/dev/ttyACM1

import os

from ament_index_python.packages import get_package_share_directory
from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument, IncludeLaunchDescription
from launch.launch_description_sources import PythonLaunchDescriptionSource
from launch.substitutions import LaunchConfiguration
from launch_ros.actions import Node


def generate_launch_description():
    dev = LaunchConfiguration("dev")
    baud = LaunchConfiguration("baud")
    return LaunchDescription([
        DeclareLaunchArgument("dev", default_value="/dev/ttyACM0",
                              description="serial device of the Arduino Nano ESP32"),
        DeclareLaunchArgument("baud", default_value="115200"),
        # started directly (not through `ros2 run`) so that Ctrl-C stops it cleanly
        # and its log lines are tagged [micro_ros_agent-1]
        Node(package="micro_ros_agent", executable="micro_ros_agent",
             arguments=["serial", "--dev", dev, "-b", baud],
             output="screen"),
        IncludeLaunchDescription(PythonLaunchDescriptionSource(os.path.join(
            get_package_share_directory("seed_imaging_cpp_pkg_bringup"), "launch",
            "SeedImagingSystem_Instance_ros2.launch.py"))),
    ])
