// #Sireum

package seedimaging.SeedImaging

import org.sireum._
import art._
import seedimaging._

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

object ScanController_Api {
  // assume SI_HOST_A1_tiltAckInRange
  //   Tilt acknowledgements lie within +/-45 deg.
  @strictpure def SI_HOST_A1_tiltAckInRange(xPos: std_msgs.Int32): B =
    SeedImaging.GUMBO__Library.isTiltSafe(xPos.data)
}

import ScanController_Api._

@sig trait ScanController_Api {
  def id: Art.BridgeId
  def start_Id : Art.PortId
  def zCmd_Id : Art.PortId
  def xCmd_Id : Art.PortId
  def yCmd_Id : Art.PortId
  def zPos_Id : Art.PortId
  def xPos_Id : Art.PortId
  def yPos_Id : Art.PortId

  // Logika spec var representing port state for outgoing event data port
  @spec var zCmd: Option[std_msgs.Int32] = $

  def put_zCmd(value : std_msgs.Int32) : Unit = {
    Contract(
      Modifies(zCmd),
      Ensures(
        zCmd == Some(value)
      )
    )
    Spec {
      zCmd = Some(value)
    }

    Art.putValue(zCmd_Id, std_msgs.Int32_Payload(value))
  }

  // Logika spec var representing port state for outgoing event data port
  @spec var xCmd: Option[std_msgs.Int32] = $

  def put_xCmd(value : std_msgs.Int32) : Unit = {
    Contract(
      Modifies(xCmd),
      Ensures(
        xCmd == Some(value)
      )
    )
    Spec {
      xCmd = Some(value)
    }

    Art.putValue(xCmd_Id, std_msgs.Int32_Payload(value))
  }

  // Logika spec var representing port state for outgoing event data port
  @spec var yCmd: Option[std_msgs.Int32] = $

  def put_yCmd(value : std_msgs.Int32) : Unit = {
    Contract(
      Modifies(yCmd),
      Ensures(
        yCmd == Some(value)
      )
    )
    Spec {
      yCmd = Some(value)
    }

    Art.putValue(yCmd_Id, std_msgs.Int32_Payload(value))
  }

  def logInfo(msg: String): Unit = {
    Art.logInfo(id, msg)
  }

  def logDebug(msg: String): Unit = {
    Art.logDebug(id, msg)
  }

  def logError(msg: String): Unit = {
    Art.logError(id, msg)
  }
}

@datatype class ScanController_Initialization_Api (
  val id: Art.BridgeId,
  val start_Id : Art.PortId,
  val zCmd_Id : Art.PortId,
  val xCmd_Id : Art.PortId,
  val yCmd_Id : Art.PortId,
  val zPos_Id : Art.PortId,
  val xPos_Id : Art.PortId,
  val yPos_Id : Art.PortId) extends ScanController_Api

@datatype class ScanController_Operational_Api (
  val id: Art.BridgeId,
  val start_Id : Art.PortId,
  val zCmd_Id : Art.PortId,
  val xCmd_Id : Art.PortId,
  val yCmd_Id : Art.PortId,
  val zPos_Id : Art.PortId,
  val xPos_Id : Art.PortId,
  val yPos_Id : Art.PortId) extends ScanController_Api {

  // Logika spec var representing port state for incoming event data port
  @spec var start: Option[std_msgs.Int32] = $

  def get_start() : Option[std_msgs.Int32] = {
    Contract(
      Ensures(
        Res == start
      )
    )
    val value : Option[std_msgs.Int32] = Art.getValue(start_Id) match {
      case Some(std_msgs.Int32_Payload(v)) => Some(v)
      case Some(v) =>
        Art.logError(id, s"Unexpected payload on port start.  Expecting 'std_msgs.Int32_Payload' but received ${v}")
        None[std_msgs.Int32]()
      case _ => None[std_msgs.Int32]()
    }
    return value
  }

  // Logika spec var representing port state for incoming event data port
  @spec var zPos: Option[std_msgs.Int32] = $

  def get_zPos() : Option[std_msgs.Int32] = {
    Contract(
      Ensures(
        Res == zPos
      )
    )
    val value : Option[std_msgs.Int32] = Art.getValue(zPos_Id) match {
      case Some(std_msgs.Int32_Payload(v)) => Some(v)
      case Some(v) =>
        Art.logError(id, s"Unexpected payload on port zPos.  Expecting 'std_msgs.Int32_Payload' but received ${v}")
        None[std_msgs.Int32]()
      case _ => None[std_msgs.Int32]()
    }
    return value
  }

  // Logika spec var representing port state for incoming event data port
  @spec var xPos: Option[std_msgs.Int32] = $
  @spec def xPos_Inv = Invariant(
    xPos.isEmpty || SI_HOST_A1_tiltAckInRange(xPos.get)
  )

  def get_xPos() : Option[std_msgs.Int32] = {
    Contract(
      Ensures(
        xPos.isEmpty || SI_HOST_A1_tiltAckInRange(xPos.get),
        Res == xPos
      )
    )
    val value : Option[std_msgs.Int32] = Art.getValue(xPos_Id) match {
      case Some(std_msgs.Int32_Payload(v)) => Some(v)
      case Some(v) =>
        Art.logError(id, s"Unexpected payload on port xPos.  Expecting 'std_msgs.Int32_Payload' but received ${v}")
        None[std_msgs.Int32]()
      case _ => None[std_msgs.Int32]()
    }
    return value
  }

  // Logika spec var representing port state for incoming event data port
  @spec var yPos: Option[std_msgs.Int32] = $

  def get_yPos() : Option[std_msgs.Int32] = {
    Contract(
      Ensures(
        Res == yPos
      )
    )
    val value : Option[std_msgs.Int32] = Art.getValue(yPos_Id) match {
      case Some(std_msgs.Int32_Payload(v)) => Some(v)
      case Some(v) =>
        Art.logError(id, s"Unexpected payload on port yPos.  Expecting 'std_msgs.Int32_Payload' but received ${v}")
        None[std_msgs.Int32]()
      case _ => None[std_msgs.Int32]()
    }
    return value
  }
}
