// #Sireum

package seedimaging.SeedImaging

import org.sireum._
import art._
import seedimaging._
import seedimaging.SeedImaging.{ScanController_jetson_scan => component}

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

@datatype class ScanController_jetson_scan_Bridge(
  val id: Art.BridgeId,
  val name: String,
  val dispatchProtocol: DispatchPropertyProtocol,
  val dispatchTriggers: Option[ISZ[Art.PortId]],

  start: Port[std_msgs.Int32],
  zCmd: Port[std_msgs.Int32],
  xCmd: Port[std_msgs.Int32],
  yCmd: Port[std_msgs.Int32],
  zPos: Port[std_msgs.Int32],
  xPos: Port[std_msgs.Int32],
  yPos: Port[std_msgs.Int32]
  ) extends Bridge {

  val ports : Bridge.Ports = Bridge.Ports(
    dataIns = ISZ[art.UPort](),

    dataOuts = ISZ[art.UPort](),

    eventIns = ISZ[art.UPort](start,
                              zPos,
                              xPos,
                              yPos),

    eventOuts = ISZ[art.UPort](zCmd,
                               xCmd,
                               yCmd)
  )

  val initialization_api : ScanController_Initialization_Api = {
    val api = ScanController_Initialization_Api(
      id,
      start.id,
      zCmd.id,
      xCmd.id,
      yCmd.id,
      zPos.id,
      xPos.id,
      yPos.id
    )
    ScanController_jetson_scan_Bridge.c_initialization_api = Some(api)
    api
  }

  val operational_api : ScanController_Operational_Api = {
    val api = ScanController_Operational_Api(
      id,
      start.id,
      zCmd.id,
      xCmd.id,
      yCmd.id,
      zPos.id,
      xPos.id,
      yPos.id
    )
    ScanController_jetson_scan_Bridge.c_operational_api = Some(api)
    api
  }

  val entryPoints : Bridge.EntryPoints =
    ScanController_jetson_scan_Bridge.EntryPoints(
      id,

      start.id,
      zCmd.id,
      xCmd.id,
      yCmd.id,
      zPos.id,
      xPos.id,
      yPos.id,

      dispatchTriggers,

      initialization_api,
      operational_api)
}

object ScanController_jetson_scan_Bridge {

  var c_initialization_api: Option[ScanController_Initialization_Api] = None()
  var c_operational_api: Option[ScanController_Operational_Api] = None()

  @datatype class EntryPoints(
    ScanController_jetson_scan_BridgeId : Art.BridgeId,
    start_Id : Art.PortId,
    zCmd_Id : Art.PortId,
    xCmd_Id : Art.PortId,
    yCmd_Id : Art.PortId,
    zPos_Id : Art.PortId,
    xPos_Id : Art.PortId,
    yPos_Id : Art.PortId,
    dispatchTriggers : Option[ISZ[Art.PortId]],
    initialization_api: ScanController_Initialization_Api,
    operational_api: ScanController_Operational_Api) extends Bridge.EntryPoints {

    val dataInPortIds: ISZ[Art.PortId] = IS()

    val eventInPortIds: ISZ[Art.PortId] = IS(start_Id,
                                             zPos_Id,
                                             xPos_Id,
                                             yPos_Id)

    val dataOutPortIds: ISZ[Art.PortId] = IS()

    val eventOutPortIds: ISZ[Art.PortId] = IS(zCmd_Id,
                                              xCmd_Id,
                                              yCmd_Id)

    def initialise(): Unit = {
      // implement the following method in 'component':  def initialise(api: ScanController_Initialization_Api): Unit = {}
      component.initialise(initialization_api)
      Art.sendOutput(eventOutPortIds, dataOutPortIds)
    }

    def compute(): Unit = {
      // transpiler friendly filter
      def filter(receivedEvents: ISZ[Art.PortId], triggers: ISZ[Art.PortId]): ISZ[Art.PortId] = {
        var r = ISZ[Art.PortId]()
        val opsTriggers = ops.ISZOps(triggers)
        for(e <- receivedEvents) {
          if(opsTriggers.contains(e)) {
            r = r :+ e
          }
        }
        return r
      }

      // fetch received events ordered by highest urgency then earliest arrival-time
      val EventTriggered(receivedEvents) = Art.dispatchStatus(ScanController_jetson_scan_BridgeId)

      // remove non-dispatching event ports
      val dispatchableEventPorts: ISZ[Art.PortId] =
        if(dispatchTriggers.isEmpty) receivedEvents
        else filter(receivedEvents, dispatchTriggers.get)

      Art.receiveInput(eventInPortIds, dataInPortIds)

      for(portId <- dispatchableEventPorts) {
        if(portId == start_Id){
          val Some(std_msgs.Int32_Payload(value)) = Art.getValue(start_Id)

          // implement the following in 'component':  def handle_start(api: ScanController_Operational_Api, value: std_msgs.Int32): Unit = {}
          component.handle_start(operational_api, value)
        }
        else if(portId == zPos_Id){
          val Some(std_msgs.Int32_Payload(value)) = Art.getValue(zPos_Id)

          // implement the following in 'component':  def handle_zPos(api: ScanController_Operational_Api, value: std_msgs.Int32): Unit = {}
          component.handle_zPos(operational_api, value)
        }
        else if(portId == xPos_Id){
          val Some(std_msgs.Int32_Payload(value)) = Art.getValue(xPos_Id)

          // implement the following in 'component':  def handle_xPos(api: ScanController_Operational_Api, value: std_msgs.Int32): Unit = {}
          component.handle_xPos(operational_api, value)
        }
        else if(portId == yPos_Id){
          val Some(std_msgs.Int32_Payload(value)) = Art.getValue(yPos_Id)

          // implement the following in 'component':  def handle_yPos(api: ScanController_Operational_Api, value: std_msgs.Int32): Unit = {}
          component.handle_yPos(operational_api, value)
        }
      }

      Art.sendOutput(eventOutPortIds, dataOutPortIds)
    }

    def finalise(): Unit = {
      // implement the following method in 'component':  def finalise(api: ScanController_Operational_Api): Unit = {}
      component.finalise(operational_api)
    }

    override
    def testInitialise(): Unit = {
      // implement the following method in 'component':  def initialise(api: ScanController_Initialization_Api): Unit = {}
      component.initialise(initialization_api)
      Art.releaseOutput(eventOutPortIds, dataOutPortIds)
    }

    override
    def testCompute(): Unit = {
      // transpiler friendly filter
      def filter(receivedEvents: ISZ[Art.PortId], triggers: ISZ[Art.PortId]): ISZ[Art.PortId] = {
        var r = ISZ[Art.PortId]()
        val opsTriggers = ops.ISZOps(triggers)
        for(e <- receivedEvents) {
          if(opsTriggers.contains(e)) {
            r = r :+ e
          }
        }
        return r
      }

      // fetch received events ordered by highest urgency then earliest arrival-time
      val EventTriggered(receivedEvents) = Art.dispatchStatus(ScanController_jetson_scan_BridgeId)

      // remove non-dispatching event ports
      val dispatchableEventPorts: ISZ[Art.PortId] =
        if(dispatchTriggers.isEmpty) receivedEvents
        else filter(receivedEvents, dispatchTriggers.get)

      Art.receiveInput(eventInPortIds, dataInPortIds)

      for(portId <- dispatchableEventPorts) {
        if(portId == start_Id){
          val Some(std_msgs.Int32_Payload(value)) = Art.getValue(start_Id)

          // implement the following in 'component':  def handle_start(api: ScanController_Operational_Api, value: std_msgs.Int32): Unit = {}
          component.handle_start(operational_api, value)
        }
        else if(portId == zPos_Id){
          val Some(std_msgs.Int32_Payload(value)) = Art.getValue(zPos_Id)

          // implement the following in 'component':  def handle_zPos(api: ScanController_Operational_Api, value: std_msgs.Int32): Unit = {}
          component.handle_zPos(operational_api, value)
        }
        else if(portId == xPos_Id){
          val Some(std_msgs.Int32_Payload(value)) = Art.getValue(xPos_Id)

          // implement the following in 'component':  def handle_xPos(api: ScanController_Operational_Api, value: std_msgs.Int32): Unit = {}
          component.handle_xPos(operational_api, value)
        }
        else if(portId == yPos_Id){
          val Some(std_msgs.Int32_Payload(value)) = Art.getValue(yPos_Id)

          // implement the following in 'component':  def handle_yPos(api: ScanController_Operational_Api, value: std_msgs.Int32): Unit = {}
          component.handle_yPos(operational_api, value)
        }
      }

      Art.releaseOutput(eventOutPortIds, dataOutPortIds)
    }
  }
}