// #Sireum

package seedimaging.SeedImaging

import org.sireum._
import seedimaging._
import org.sireum.S32._

// Do not edit this file as it will be overwritten if HAMR codegen is rerun
object ScanController_jetson_scan_GumboX {
  /** I-Assm: Integration constraint on scan's incoming event data port xPos
    *
    * assume SI_HOST_A1_tiltAckInRange
    *   Tilt acknowledgements lie within +/-45 deg.
    */
  @strictpure def I_Assm_xPos(xPos: std_msgs.Int32): B =
    SeedImaging.GUMBO__Library.isTiltSafe(xPos.data)

  // I-Assm-Guard: Integration constraint on scan's incoming event data port xPos
  @strictpure def I_Assm_Guard_xPos(xPos: Option[std_msgs.Int32]): B =
    xPos.nonEmpty ___>: I_Assm_xPos(xPos.get)

  /** Initialize Entrypoint Contract
    *
    * guarantee SI_HOST_1_startIdle
    *   SI-HOST-1: The scan controller starts idle: no move in flight, tilt assumed level, plan at its first move.
    * @param awaitAxis post-state state variable
    * @param halted post-state state variable
    * @param pending post-state state variable
    * @param planEnd post-state state variable
    * @param planIndex post-state state variable
    * @param tiltEstimate post-state state variable
    */
  @strictpure def initialize_SI_HOST_1_startIdle (
      awaitAxis: Base_Types.Integer_32,
      halted: Base_Types.Boolean,
      pending: Base_Types.Boolean,
      planEnd: Base_Types.Integer_32,
      planIndex: Base_Types.Integer_32,
      tiltEstimate: Base_Types.Integer_32): B =
    !pending &
      awaitAxis == s32"0" &
      tiltEstimate == s32"0" &
      planIndex == s32"0" &
      planEnd == s32"0" &
      !halted

  /** IEP-Guar: Initialize Entrypoint Contracts for scan
    *
    * @param awaitAxis post-state state variable
    * @param halted post-state state variable
    * @param pending post-state state variable
    * @param planEnd post-state state variable
    * @param planIndex post-state state variable
    * @param tiltEstimate post-state state variable
    * @param api_xCmd outgoing event data port
    * @param api_yCmd outgoing event data port
    * @param api_zCmd outgoing event data port
    */
  @strictpure def initialize_IEP_Guar (
      awaitAxis: Base_Types.Integer_32,
      halted: Base_Types.Boolean,
      pending: Base_Types.Boolean,
      planEnd: Base_Types.Integer_32,
      planIndex: Base_Types.Integer_32,
      tiltEstimate: Base_Types.Integer_32,
      api_xCmd: Option[std_msgs.Int32],
      api_yCmd: Option[std_msgs.Int32],
      api_zCmd: Option[std_msgs.Int32]): B =
    initialize_SI_HOST_1_startIdle(awaitAxis, halted, pending, planEnd, planIndex, tiltEstimate)

  /** IEP-Post: Initialize Entrypoint Post-Condition
    *
    * @param awaitAxis post-state state variable
    * @param halted post-state state variable
    * @param pending post-state state variable
    * @param planEnd post-state state variable
    * @param planIndex post-state state variable
    * @param tiltEstimate post-state state variable
    * @param api_xCmd outgoing event data port
    * @param api_yCmd outgoing event data port
    * @param api_zCmd outgoing event data port
    */
  @strictpure def inititialize_IEP_Post (
      awaitAxis: Base_Types.Integer_32,
      halted: Base_Types.Boolean,
      pending: Base_Types.Boolean,
      planEnd: Base_Types.Integer_32,
      planIndex: Base_Types.Integer_32,
      tiltEstimate: Base_Types.Integer_32,
      api_xCmd: Option[std_msgs.Int32],
      api_yCmd: Option[std_msgs.Int32],
      api_zCmd: Option[std_msgs.Int32]): B =
    {
      // IEP-Guar: Initialize Entrypoint contract for scan
      initialize_IEP_Guar(awaitAxis, halted, pending, planEnd, planIndex, tiltEstimate, api_xCmd, api_yCmd, api_zCmd)
    }

  /** IEP-Post: Initialize Entrypoint Post-Condition via container
    *
    * @param post Container holding the value of incoming ports and the pre-state values of state variables
    */
  @strictpure def inititialize_IEP_Post_Container (post: ScanController_jetson_scan_PostState_Container_PS): B =
    inititialize_IEP_Post (
      awaitAxis = post.awaitAxis,
      halted = post.halted,
      pending = post.pending,
      planEnd = post.planEnd,
      planIndex = post.planIndex,
      tiltEstimate = post.tiltEstimate,
      api_xCmd = post.api_xCmd,
      api_yCmd = post.api_yCmd,
      api_zCmd = post.api_zCmd)

  /** Compute Entrypoint Contract
    *
    * assume SI_HOST_A2_stateInRange
    *   The controller's state is within range when an event arrives.
    * @param In_awaitAxis pre-state state variable
    * @param In_planEnd pre-state state variable
    * @param In_planIndex pre-state state variable
    * @param In_tiltEstimate pre-state state variable
    */
  @strictpure def compute_spec_SI_HOST_A2_stateInRange_assume(
      In_awaitAxis: Base_Types.Integer_32,
      In_planEnd: Base_Types.Integer_32,
      In_planIndex: Base_Types.Integer_32,
      In_tiltEstimate: Base_Types.Integer_32): B =
    SeedImaging.GUMBO__Library.isTiltSafe(In_tiltEstimate) & ScanController_jetson_scan.isAxis(In_awaitAxis) &
      s32"0" <= In_planIndex &
      In_planIndex <= In_planEnd &
      In_planEnd <= SeedImaging.GUMBO__Library.MAX_SCAN_MOVES()

  /** CEP-T-Assm: Top-level assume contracts for scan's compute entrypoint
    *
    * @param In_awaitAxis pre-state state variable
    * @param In_planEnd pre-state state variable
    * @param In_planIndex pre-state state variable
    * @param In_tiltEstimate pre-state state variable
    */
  @strictpure def compute_CEP_T_Assm (
      In_awaitAxis: Base_Types.Integer_32,
      In_planEnd: Base_Types.Integer_32,
      In_planIndex: Base_Types.Integer_32,
      In_tiltEstimate: Base_Types.Integer_32): B =
    compute_spec_SI_HOST_A2_stateInRange_assume(In_awaitAxis, In_planEnd, In_planIndex, In_tiltEstimate)

  /** CEP-Pre: Compute Entrypoint Pre-Condition for scan
    *
    * @param In_awaitAxis pre-state state variable
    * @param In_halted pre-state state variable
    * @param In_pending pre-state state variable
    * @param In_planEnd pre-state state variable
    * @param In_planIndex pre-state state variable
    * @param In_tiltEstimate pre-state state variable
    * @param api_start incoming event data port
    * @param api_xPos incoming event data port
    * @param api_yPos incoming event data port
    * @param api_zPos incoming event data port
    */
  @strictpure def compute_CEP_Pre (
      In_awaitAxis: Base_Types.Integer_32,
      In_halted: Base_Types.Boolean,
      In_pending: Base_Types.Boolean,
      In_planEnd: Base_Types.Integer_32,
      In_planIndex: Base_Types.Integer_32,
      In_tiltEstimate: Base_Types.Integer_32,
      api_start: Option[std_msgs.Int32],
      api_xPos: Option[std_msgs.Int32],
      api_yPos: Option[std_msgs.Int32],
      api_zPos: Option[std_msgs.Int32]): B =
    {
      // I-Assm-Guard: Integration constraints for scan's incoming ports
      val r0 = I_Assm_Guard_xPos(api_xPos)

      // CEP-Assm: assume clauses of scan's compute entrypoint
      val r1 = compute_CEP_T_Assm (In_awaitAxis, In_planEnd, In_planIndex, In_tiltEstimate)

      r0 & r1
    }

  /** CEP-Pre: Compute Entrypoint Pre-Condition for scan via container
    *
    * @param pre Container holding the value of incoming ports and the pre-state values of state variables
    */
  @strictpure def compute_CEP_Pre_Container(pre: ScanController_jetson_scan_PreState_Container_PS): B =
    compute_CEP_Pre(
      In_awaitAxis = pre.In_awaitAxis,
      In_halted = pre.In_halted,
      In_pending = pre.In_pending,
      In_planEnd = pre.In_planEnd,
      In_planIndex = pre.In_planIndex,
      In_tiltEstimate = pre.In_tiltEstimate,
      api_start = pre.api_start,
      api_xPos = pre.api_xPos,
      api_yPos = pre.api_yPos,
      api_zPos = pre.api_zPos)

  /** Compute Entrypoint Contract
    *
    * guarantee SI_HOST_2_oneCommandPerDispatch
    *   SI-HOST-2: At most one move command is issued per dispatch.
    * @param api_xCmd outgoing event data port
    * @param api_yCmd outgoing event data port
    * @param api_zCmd outgoing event data port
    */
  @strictpure def compute_spec_SI_HOST_2_oneCommandPerDispatch_guarantee(
      api_xCmd: Option[std_msgs.Int32],
      api_yCmd: Option[std_msgs.Int32],
      api_zCmd: Option[std_msgs.Int32]): B =
    (api_zCmd.nonEmpty __>:
       api_xCmd.isEmpty & api_yCmd.isEmpty) &
      (api_xCmd.nonEmpty __>: api_yCmd.isEmpty)

  /** Compute Entrypoint Contract
    *
    * guarantee SI_HOST_3_oneMoveInFlight
    *   SI-HOST-3: While a move is unacknowledged, no new move is issued unless this very event is its acknowledgement.
    * @param In_awaitAxis pre-state state variable
    * @param In_pending pre-state state variable
    * @param api_xPos incoming event data port
    * @param api_yPos incoming event data port
    * @param api_zPos incoming event data port
    * @param api_xCmd outgoing event data port
    * @param api_yCmd outgoing event data port
    * @param api_zCmd outgoing event data port
    */
  @strictpure def compute_spec_SI_HOST_3_oneMoveInFlight_guarantee(
      In_awaitAxis: Base_Types.Integer_32,
      In_pending: Base_Types.Boolean,
      api_xPos: Option[std_msgs.Int32],
      api_yPos: Option[std_msgs.Int32],
      api_zPos: Option[std_msgs.Int32],
      api_xCmd: Option[std_msgs.Int32],
      api_yCmd: Option[std_msgs.Int32],
      api_zCmd: Option[std_msgs.Int32]): B =
    In_pending & !(api_zPos.nonEmpty &
       In_awaitAxis == s32"0" |
       api_xPos.nonEmpty &
         In_awaitAxis == s32"1" |
       api_yPos.nonEmpty &
         In_awaitAxis == s32"2") __>:
      api_zCmd.isEmpty & api_xCmd.isEmpty &
        api_yCmd.isEmpty

  /** Compute Entrypoint Contract
    *
    * guarantee SI_HOST_4_tiltCommandsSafe
    *   SI-HOST-4: A tilt command is only issued if it is bounded and its target stays within +/-45 deg.
    * @param tiltEstimate post-state state variable
    * @param api_xCmd outgoing event data port
    */
  @strictpure def compute_spec_SI_HOST_4_tiltCommandsSafe_guarantee(
      tiltEstimate: Base_Types.Integer_32,
      api_xCmd: Option[std_msgs.Int32]): B =
    api_xCmd.isEmpty || SeedImaging.GUMBO__Library.isSafeTiltMove(tiltEstimate, api_xCmd.get.data)

  /** Compute Entrypoint Contract
    *
    * guarantee SI_HOST_6_awaitCommandedAxis
    *   SI-HOST-6: Issuing a move makes it the move in flight, on the commanded axis.
    * @param awaitAxis post-state state variable
    * @param pending post-state state variable
    * @param api_xCmd outgoing event data port
    * @param api_yCmd outgoing event data port
    * @param api_zCmd outgoing event data port
    */
  @strictpure def compute_spec_SI_HOST_6_awaitCommandedAxis_guarantee(
      awaitAxis: Base_Types.Integer_32,
      pending: Base_Types.Boolean,
      api_xCmd: Option[std_msgs.Int32],
      api_yCmd: Option[std_msgs.Int32],
      api_zCmd: Option[std_msgs.Int32]): B =
    (api_zCmd.nonEmpty __>:
       pending &
         awaitAxis == s32"0") &
      (api_xCmd.nonEmpty __>:
        pending &
          awaitAxis == s32"1") &
      (api_yCmd.nonEmpty __>:
        pending &
          awaitAxis == s32"2")

  /** Compute Entrypoint Contract
    *
    * guarantee SI_HOST_7_stateInRange
    *   SI-HOST-7: The awaited axis and the plan position stay within range (a plan never exceeds MAX_SCAN_MOVES moves).
    * @param awaitAxis post-state state variable
    * @param planEnd post-state state variable
    * @param planIndex post-state state variable
    */
  @strictpure def compute_spec_SI_HOST_7_stateInRange_guarantee(
      awaitAxis: Base_Types.Integer_32,
      planEnd: Base_Types.Integer_32,
      planIndex: Base_Types.Integer_32): B =
    ScanController_jetson_scan.isAxis(awaitAxis) &
      s32"0" <= planIndex &
      planIndex <= planEnd &
      planEnd <= SeedImaging.GUMBO__Library.MAX_SCAN_MOVES()

  /** Compute Entrypoint Contract
    *
    * guarantee SI_HOST_8_haltIsFinal
    *   SI-HOST-8: Once halted, the scan controller stays halted and issues no further moves.
    * @param In_halted pre-state state variable
    * @param halted post-state state variable
    * @param api_xCmd outgoing event data port
    * @param api_yCmd outgoing event data port
    * @param api_zCmd outgoing event data port
    */
  @strictpure def compute_spec_SI_HOST_8_haltIsFinal_guarantee(
      In_halted: Base_Types.Boolean,
      halted: Base_Types.Boolean,
      api_xCmd: Option[std_msgs.Int32],
      api_yCmd: Option[std_msgs.Int32],
      api_zCmd: Option[std_msgs.Int32]): B =
    In_halted __>:
      halted & api_zCmd.isEmpty &
        api_xCmd.isEmpty &
        api_yCmd.isEmpty

  /** Compute Entrypoint Contract
    *
    * guarantee SI_HOST_9_noMoveNoPending
    *   SI-HOST-9: If no move is issued, a move is pending only if one already was.
    * @param In_pending pre-state state variable
    * @param pending post-state state variable
    * @param api_xCmd outgoing event data port
    * @param api_yCmd outgoing event data port
    * @param api_zCmd outgoing event data port
    */
  @strictpure def compute_spec_SI_HOST_9_noMoveNoPending_guarantee(
      In_pending: Base_Types.Boolean,
      pending: Base_Types.Boolean,
      api_xCmd: Option[std_msgs.Int32],
      api_yCmd: Option[std_msgs.Int32],
      api_zCmd: Option[std_msgs.Int32]): B =
    !(ScanController_jetson_scan.cmdSent(api_zCmd.nonEmpty, api_xCmd.nonEmpty, api_yCmd.nonEmpty)) __>:
      pending __>: In_pending

  /** Compute Entrypoint Contract
    *
    * guarantee SI_HOST_10_tiltEstimateInRange
    *   SI-HOST-10: The tilt estimate always lies within +/-45 deg.
    * @param tiltEstimate post-state state variable
    */
  @strictpure def compute_spec_SI_HOST_10_tiltEstimateInRange_guarantee(
      tiltEstimate: Base_Types.Integer_32): B =
    SeedImaging.GUMBO__Library.isTiltSafe(tiltEstimate)

  /** CEP-T-Guar: Top-level guarantee contracts for scan's compute entrypoint
    *
    * @param In_awaitAxis pre-state state variable
    * @param In_halted pre-state state variable
    * @param In_pending pre-state state variable
    * @param awaitAxis post-state state variable
    * @param halted post-state state variable
    * @param pending post-state state variable
    * @param planEnd post-state state variable
    * @param planIndex post-state state variable
    * @param tiltEstimate post-state state variable
    * @param api_xPos incoming event data port
    * @param api_yPos incoming event data port
    * @param api_zPos incoming event data port
    * @param api_xCmd outgoing event data port
    * @param api_yCmd outgoing event data port
    * @param api_zCmd outgoing event data port
    */
  @strictpure def compute_CEP_T_Guar (
      In_awaitAxis: Base_Types.Integer_32,
      In_halted: Base_Types.Boolean,
      In_pending: Base_Types.Boolean,
      awaitAxis: Base_Types.Integer_32,
      halted: Base_Types.Boolean,
      pending: Base_Types.Boolean,
      planEnd: Base_Types.Integer_32,
      planIndex: Base_Types.Integer_32,
      tiltEstimate: Base_Types.Integer_32,
      api_xPos: Option[std_msgs.Int32],
      api_yPos: Option[std_msgs.Int32],
      api_zPos: Option[std_msgs.Int32],
      api_xCmd: Option[std_msgs.Int32],
      api_yCmd: Option[std_msgs.Int32],
      api_zCmd: Option[std_msgs.Int32]): B =
    {
      val r0 = compute_spec_SI_HOST_2_oneCommandPerDispatch_guarantee(api_xCmd, api_yCmd, api_zCmd)
      val r1 = compute_spec_SI_HOST_3_oneMoveInFlight_guarantee(In_awaitAxis, In_pending, api_xPos, api_yPos, api_zPos, api_xCmd, api_yCmd, api_zCmd)
      val r2 = compute_spec_SI_HOST_4_tiltCommandsSafe_guarantee(tiltEstimate, api_xCmd)
      val r3 = compute_spec_SI_HOST_6_awaitCommandedAxis_guarantee(awaitAxis, pending, api_xCmd, api_yCmd, api_zCmd)
      val r4 = compute_spec_SI_HOST_7_stateInRange_guarantee(awaitAxis, planEnd, planIndex)
      val r5 = compute_spec_SI_HOST_8_haltIsFinal_guarantee(In_halted, halted, api_xCmd, api_yCmd, api_zCmd)
      val r6 = compute_spec_SI_HOST_9_noMoveNoPending_guarantee(In_pending, pending, api_xCmd, api_yCmd, api_zCmd)
      val r7 = compute_spec_SI_HOST_10_tiltEstimateInRange_guarantee(tiltEstimate)

      r0 & r1 & r2 & r3 & r4 & r5 & r6 & r7
    }

  /** Compute Entrypoint Contract for start's SI_HOST_11_startIgnoredWhenBusy guarantee clause
    *
    * guarantee SI_HOST_11_startIgnoredWhenBusy
    *   SI-HOST-11: A start request while a move is in flight, or after a halt, changes nothing.
    * @param In_awaitAxis pre-state state variable
    * @param In_halted pre-state state variable
    * @param In_pending pre-state state variable
    * @param In_planEnd pre-state state variable
    * @param In_planIndex pre-state state variable
    * @param awaitAxis post-state state variable
    * @param halted post-state state variable
    * @param pending post-state state variable
    * @param planEnd post-state state variable
    * @param planIndex post-state state variable
    * @param api_xCmd outgoing event data port
    * @param api_yCmd outgoing event data port
    * @param api_zCmd outgoing event data port
    */
  @strictpure def compute_handle_start_SI_HOST_11_startIgnoredWhenBusy_guarantee(
      In_awaitAxis: Base_Types.Integer_32,
      In_halted: Base_Types.Boolean,
      In_pending: Base_Types.Boolean,
      In_planEnd: Base_Types.Integer_32,
      In_planIndex: Base_Types.Integer_32,
      awaitAxis: Base_Types.Integer_32,
      halted: Base_Types.Boolean,
      pending: Base_Types.Boolean,
      planEnd: Base_Types.Integer_32,
      planIndex: Base_Types.Integer_32,
      api_xCmd: Option[std_msgs.Int32],
      api_yCmd: Option[std_msgs.Int32],
      api_zCmd: Option[std_msgs.Int32]): B =
    In_pending | In_halted __>:
      api_zCmd.isEmpty & api_xCmd.isEmpty &
        api_yCmd.isEmpty &
        pending == In_pending &
        awaitAxis == In_awaitAxis &
        planIndex == In_planIndex &
        planEnd == In_planEnd &
        halted == In_halted

  /** Compute Entrypoint Contract for start's SI_HOST_5_startKeepsTilt guarantee clause
    *
    * guarantee SI_HOST_5_startKeepsTilt
    *   SI-HOST-5: The tilt estimate changes only on a tilt acknowledgement.
    * @param In_tiltEstimate pre-state state variable
    * @param tiltEstimate post-state state variable
    */
  @strictpure def compute_handle_start_SI_HOST_5_startKeepsTilt_guarantee(
      In_tiltEstimate: Base_Types.Integer_32,
      tiltEstimate: Base_Types.Integer_32): B =
    tiltEstimate == In_tiltEstimate

  /** Compute Entrypoint Contract for start's SI_HOST_12_startLaunchesPlan guarantee clause
    *
    * guarantee SI_HOST_12_startLaunchesPlan
    *   SI-HOST-12: A start request while idle launches the selected plan: its first move is issued, or the scan halts.
    * @param In_halted pre-state state variable
    * @param In_pending pre-state state variable
    * @param halted post-state state variable
    * @param api_xCmd outgoing event data port
    * @param api_yCmd outgoing event data port
    * @param api_zCmd outgoing event data port
    */
  @strictpure def compute_handle_start_SI_HOST_12_startLaunchesPlan_guarantee(
      In_halted: Base_Types.Boolean,
      In_pending: Base_Types.Boolean,
      halted: Base_Types.Boolean,
      api_xCmd: Option[std_msgs.Int32],
      api_yCmd: Option[std_msgs.Int32],
      api_zCmd: Option[std_msgs.Int32]): B =
    !In_pending & !In_halted __>:
      ScanController_jetson_scan.cmdSent(api_zCmd.nonEmpty, api_xCmd.nonEmpty, api_yCmd.nonEmpty) | halted

  /** CEP-T-Handle_start_Guar: Top-level guarantee contracts for scan's compute start handler
    *
    * @param In_awaitAxis pre-state state variable
    * @param In_halted pre-state state variable
    * @param In_pending pre-state state variable
    * @param In_planEnd pre-state state variable
    * @param In_planIndex pre-state state variable
    * @param In_tiltEstimate pre-state state variable
    * @param awaitAxis post-state state variable
    * @param halted post-state state variable
    * @param pending post-state state variable
    * @param planEnd post-state state variable
    * @param planIndex post-state state variable
    * @param tiltEstimate post-state state variable
    * @param api_start incoming event data port
    * @param api_xCmd outgoing event data port
    * @param api_yCmd outgoing event data port
    * @param api_zCmd outgoing event data port
    */
  @strictpure def compute_CEP_Handler_start_Guar (
      In_awaitAxis: Base_Types.Integer_32,
      In_halted: Base_Types.Boolean,
      In_pending: Base_Types.Boolean,
      In_planEnd: Base_Types.Integer_32,
      In_planIndex: Base_Types.Integer_32,
      In_tiltEstimate: Base_Types.Integer_32,
      awaitAxis: Base_Types.Integer_32,
      halted: Base_Types.Boolean,
      pending: Base_Types.Boolean,
      planEnd: Base_Types.Integer_32,
      planIndex: Base_Types.Integer_32,
      tiltEstimate: Base_Types.Integer_32,
      api_start: Option[std_msgs.Int32],
      api_xCmd: Option[std_msgs.Int32],
      api_yCmd: Option[std_msgs.Int32],
      api_zCmd: Option[std_msgs.Int32]): B = {
    if (api_start.isEmpty) {
      T
    } else
    {
      val r0 = compute_handle_start_SI_HOST_11_startIgnoredWhenBusy_guarantee(In_awaitAxis, In_halted, In_pending, In_planEnd, In_planIndex, awaitAxis, halted, pending, planEnd, planIndex, api_xCmd, api_yCmd, api_zCmd)
      val r1 = compute_handle_start_SI_HOST_5_startKeepsTilt_guarantee(In_tiltEstimate, tiltEstimate)
      val r2 = compute_handle_start_SI_HOST_12_startLaunchesPlan_guarantee(In_halted, In_pending, halted, api_xCmd, api_yCmd, api_zCmd)

      r0 & r1 & r2
    }
  }

  /** Compute Entrypoint Contract for zPos's SI_HOST_5_zKeepsTilt guarantee clause
    *
    * guarantee SI_HOST_5_zKeepsTilt
    *   SI-HOST-5: The tilt estimate changes only on a tilt acknowledgement.
    * @param In_tiltEstimate pre-state state variable
    * @param tiltEstimate post-state state variable
    */
  @strictpure def compute_handle_zPos_SI_HOST_5_zKeepsTilt_guarantee(
      In_tiltEstimate: Base_Types.Integer_32,
      tiltEstimate: Base_Types.Integer_32): B =
    tiltEstimate == In_tiltEstimate

  /** Compute Entrypoint Contract for zPos's SI_HOST_13_zStrayAckIgnored guarantee clause
    *
    * guarantee SI_HOST_13_zStrayAckIgnored
    *   SI-HOST-13: A turntable acknowledgement that is not awaited changes nothing and issues nothing.
    * @param In_awaitAxis pre-state state variable
    * @param In_halted pre-state state variable
    * @param In_pending pre-state state variable
    * @param In_planEnd pre-state state variable
    * @param In_planIndex pre-state state variable
    * @param awaitAxis post-state state variable
    * @param halted post-state state variable
    * @param pending post-state state variable
    * @param planEnd post-state state variable
    * @param planIndex post-state state variable
    * @param api_xCmd outgoing event data port
    * @param api_yCmd outgoing event data port
    * @param api_zCmd outgoing event data port
    */
  @strictpure def compute_handle_zPos_SI_HOST_13_zStrayAckIgnored_guarantee(
      In_awaitAxis: Base_Types.Integer_32,
      In_halted: Base_Types.Boolean,
      In_pending: Base_Types.Boolean,
      In_planEnd: Base_Types.Integer_32,
      In_planIndex: Base_Types.Integer_32,
      awaitAxis: Base_Types.Integer_32,
      halted: Base_Types.Boolean,
      pending: Base_Types.Boolean,
      planEnd: Base_Types.Integer_32,
      planIndex: Base_Types.Integer_32,
      api_xCmd: Option[std_msgs.Int32],
      api_yCmd: Option[std_msgs.Int32],
      api_zCmd: Option[std_msgs.Int32]): B =
    !(In_pending &
       In_awaitAxis == s32"0") __>:
      api_zCmd.isEmpty & api_xCmd.isEmpty &
        api_yCmd.isEmpty &
        pending == In_pending &
        awaitAxis == In_awaitAxis &
        planIndex == In_planIndex &
        planEnd == In_planEnd &
        halted == In_halted

  /** Compute Entrypoint Contract for zPos's SI_HOST_14_zAckAdvancesPlan guarantee clause
    *
    * guarantee SI_HOST_14_zAckAdvancesPlan
    *   SI-HOST-14: The awaited turntable acknowledgement completes the move; the next move (if any) advances the plan by one.
    * @param In_awaitAxis pre-state state variable
    * @param In_pending pre-state state variable
    * @param In_planEnd pre-state state variable
    * @param In_planIndex pre-state state variable
    * @param pending post-state state variable
    * @param planEnd post-state state variable
    * @param planIndex post-state state variable
    * @param api_xCmd outgoing event data port
    * @param api_yCmd outgoing event data port
    * @param api_zCmd outgoing event data port
    */
  @strictpure def compute_handle_zPos_SI_HOST_14_zAckAdvancesPlan_guarantee(
      In_awaitAxis: Base_Types.Integer_32,
      In_pending: Base_Types.Boolean,
      In_planEnd: Base_Types.Integer_32,
      In_planIndex: Base_Types.Integer_32,
      pending: Base_Types.Boolean,
      planEnd: Base_Types.Integer_32,
      planIndex: Base_Types.Integer_32,
      api_xCmd: Option[std_msgs.Int32],
      api_yCmd: Option[std_msgs.Int32],
      api_zCmd: Option[std_msgs.Int32]): B =
    In_pending &
      In_awaitAxis == s32"0" __>:
      (ScanController_jetson_scan.cmdSent(api_zCmd.nonEmpty, api_xCmd.nonEmpty, api_yCmd.nonEmpty) __>:
        planIndex == In_planIndex + s32"1") &
        (!(ScanController_jetson_scan.cmdSent(api_zCmd.nonEmpty, api_xCmd.nonEmpty, api_yCmd.nonEmpty)) __>:
          !pending &
            planIndex == In_planIndex) &
        planEnd == In_planEnd

  /** CEP-T-Handle_zPos_Guar: Top-level guarantee contracts for scan's compute zPos handler
    *
    * @param In_awaitAxis pre-state state variable
    * @param In_halted pre-state state variable
    * @param In_pending pre-state state variable
    * @param In_planEnd pre-state state variable
    * @param In_planIndex pre-state state variable
    * @param In_tiltEstimate pre-state state variable
    * @param awaitAxis post-state state variable
    * @param halted post-state state variable
    * @param pending post-state state variable
    * @param planEnd post-state state variable
    * @param planIndex post-state state variable
    * @param tiltEstimate post-state state variable
    * @param api_zPos incoming event data port
    * @param api_xCmd outgoing event data port
    * @param api_yCmd outgoing event data port
    * @param api_zCmd outgoing event data port
    */
  @strictpure def compute_CEP_Handler_zPos_Guar (
      In_awaitAxis: Base_Types.Integer_32,
      In_halted: Base_Types.Boolean,
      In_pending: Base_Types.Boolean,
      In_planEnd: Base_Types.Integer_32,
      In_planIndex: Base_Types.Integer_32,
      In_tiltEstimate: Base_Types.Integer_32,
      awaitAxis: Base_Types.Integer_32,
      halted: Base_Types.Boolean,
      pending: Base_Types.Boolean,
      planEnd: Base_Types.Integer_32,
      planIndex: Base_Types.Integer_32,
      tiltEstimate: Base_Types.Integer_32,
      api_zPos: Option[std_msgs.Int32],
      api_xCmd: Option[std_msgs.Int32],
      api_yCmd: Option[std_msgs.Int32],
      api_zCmd: Option[std_msgs.Int32]): B = {
    if (api_zPos.isEmpty) {
      T
    } else
    {
      val r0 = compute_handle_zPos_SI_HOST_5_zKeepsTilt_guarantee(In_tiltEstimate, tiltEstimate)
      val r1 = compute_handle_zPos_SI_HOST_13_zStrayAckIgnored_guarantee(In_awaitAxis, In_halted, In_pending, In_planEnd, In_planIndex, awaitAxis, halted, pending, planEnd, planIndex, api_xCmd, api_yCmd, api_zCmd)
      val r2 = compute_handle_zPos_SI_HOST_14_zAckAdvancesPlan_guarantee(In_awaitAxis, In_pending, In_planEnd, In_planIndex, pending, planEnd, planIndex, api_xCmd, api_yCmd, api_zCmd)

      r0 & r1 & r2
    }
  }

  /** Compute Entrypoint Contract for xPos's SI_HOST_5_xTracksTilt guarantee clause
    *
    * guarantee SI_HOST_5_xTracksTilt
    *   SI-HOST-5: A tilt acknowledgement always updates the tilt estimate to the reported position.
    * @param tiltEstimate post-state state variable
    * @param api_xPos incoming event data port
    */
  @strictpure def compute_handle_xPos_SI_HOST_5_xTracksTilt_guarantee(
      tiltEstimate: Base_Types.Integer_32,
      api_xPos: Option[std_msgs.Int32]): B =
    tiltEstimate == api_xPos.get.data

  /** Compute Entrypoint Contract for xPos's SI_HOST_15_xStrayAckIgnored guarantee clause
    *
    * guarantee SI_HOST_15_xStrayAckIgnored
    *   SI-HOST-15: A tilt acknowledgement that is not awaited only updates the tilt estimate.
    * @param In_awaitAxis pre-state state variable
    * @param In_halted pre-state state variable
    * @param In_pending pre-state state variable
    * @param In_planEnd pre-state state variable
    * @param In_planIndex pre-state state variable
    * @param awaitAxis post-state state variable
    * @param halted post-state state variable
    * @param pending post-state state variable
    * @param planEnd post-state state variable
    * @param planIndex post-state state variable
    * @param api_xCmd outgoing event data port
    * @param api_yCmd outgoing event data port
    * @param api_zCmd outgoing event data port
    */
  @strictpure def compute_handle_xPos_SI_HOST_15_xStrayAckIgnored_guarantee(
      In_awaitAxis: Base_Types.Integer_32,
      In_halted: Base_Types.Boolean,
      In_pending: Base_Types.Boolean,
      In_planEnd: Base_Types.Integer_32,
      In_planIndex: Base_Types.Integer_32,
      awaitAxis: Base_Types.Integer_32,
      halted: Base_Types.Boolean,
      pending: Base_Types.Boolean,
      planEnd: Base_Types.Integer_32,
      planIndex: Base_Types.Integer_32,
      api_xCmd: Option[std_msgs.Int32],
      api_yCmd: Option[std_msgs.Int32],
      api_zCmd: Option[std_msgs.Int32]): B =
    !(In_pending &
       In_awaitAxis == s32"1") __>:
      api_zCmd.isEmpty & api_xCmd.isEmpty &
        api_yCmd.isEmpty &
        pending == In_pending &
        awaitAxis == In_awaitAxis &
        planIndex == In_planIndex &
        planEnd == In_planEnd &
        halted == In_halted

  /** Compute Entrypoint Contract for xPos's SI_HOST_16_xAckAdvancesPlan guarantee clause
    *
    * guarantee SI_HOST_16_xAckAdvancesPlan
    *   SI-HOST-16: The awaited tilt acknowledgement completes the move; the next move (if any) advances the plan by one.
    * @param In_awaitAxis pre-state state variable
    * @param In_pending pre-state state variable
    * @param In_planEnd pre-state state variable
    * @param In_planIndex pre-state state variable
    * @param pending post-state state variable
    * @param planEnd post-state state variable
    * @param planIndex post-state state variable
    * @param api_xCmd outgoing event data port
    * @param api_yCmd outgoing event data port
    * @param api_zCmd outgoing event data port
    */
  @strictpure def compute_handle_xPos_SI_HOST_16_xAckAdvancesPlan_guarantee(
      In_awaitAxis: Base_Types.Integer_32,
      In_pending: Base_Types.Boolean,
      In_planEnd: Base_Types.Integer_32,
      In_planIndex: Base_Types.Integer_32,
      pending: Base_Types.Boolean,
      planEnd: Base_Types.Integer_32,
      planIndex: Base_Types.Integer_32,
      api_xCmd: Option[std_msgs.Int32],
      api_yCmd: Option[std_msgs.Int32],
      api_zCmd: Option[std_msgs.Int32]): B =
    In_pending &
      In_awaitAxis == s32"1" __>:
      (ScanController_jetson_scan.cmdSent(api_zCmd.nonEmpty, api_xCmd.nonEmpty, api_yCmd.nonEmpty) __>:
        planIndex == In_planIndex + s32"1") &
        (!(ScanController_jetson_scan.cmdSent(api_zCmd.nonEmpty, api_xCmd.nonEmpty, api_yCmd.nonEmpty)) __>:
          !pending &
            planIndex == In_planIndex) &
        planEnd == In_planEnd

  /** CEP-T-Handle_xPos_Guar: Top-level guarantee contracts for scan's compute xPos handler
    *
    * @param In_awaitAxis pre-state state variable
    * @param In_halted pre-state state variable
    * @param In_pending pre-state state variable
    * @param In_planEnd pre-state state variable
    * @param In_planIndex pre-state state variable
    * @param awaitAxis post-state state variable
    * @param halted post-state state variable
    * @param pending post-state state variable
    * @param planEnd post-state state variable
    * @param planIndex post-state state variable
    * @param tiltEstimate post-state state variable
    * @param api_xPos incoming event data port
    * @param api_xCmd outgoing event data port
    * @param api_yCmd outgoing event data port
    * @param api_zCmd outgoing event data port
    */
  @strictpure def compute_CEP_Handler_xPos_Guar (
      In_awaitAxis: Base_Types.Integer_32,
      In_halted: Base_Types.Boolean,
      In_pending: Base_Types.Boolean,
      In_planEnd: Base_Types.Integer_32,
      In_planIndex: Base_Types.Integer_32,
      awaitAxis: Base_Types.Integer_32,
      halted: Base_Types.Boolean,
      pending: Base_Types.Boolean,
      planEnd: Base_Types.Integer_32,
      planIndex: Base_Types.Integer_32,
      tiltEstimate: Base_Types.Integer_32,
      api_xPos: Option[std_msgs.Int32],
      api_xCmd: Option[std_msgs.Int32],
      api_yCmd: Option[std_msgs.Int32],
      api_zCmd: Option[std_msgs.Int32]): B = {
    if (api_xPos.isEmpty) {
      T
    } else
    {
      val r0 = compute_handle_xPos_SI_HOST_5_xTracksTilt_guarantee(tiltEstimate, api_xPos)
      val r1 = compute_handle_xPos_SI_HOST_15_xStrayAckIgnored_guarantee(In_awaitAxis, In_halted, In_pending, In_planEnd, In_planIndex, awaitAxis, halted, pending, planEnd, planIndex, api_xCmd, api_yCmd, api_zCmd)
      val r2 = compute_handle_xPos_SI_HOST_16_xAckAdvancesPlan_guarantee(In_awaitAxis, In_pending, In_planEnd, In_planIndex, pending, planEnd, planIndex, api_xCmd, api_yCmd, api_zCmd)

      r0 & r1 & r2
    }
  }

  /** Compute Entrypoint Contract for yPos's SI_HOST_5_yKeepsTilt guarantee clause
    *
    * guarantee SI_HOST_5_yKeepsTilt
    *   SI-HOST-5: The tilt estimate changes only on a tilt acknowledgement.
    * @param In_tiltEstimate pre-state state variable
    * @param tiltEstimate post-state state variable
    */
  @strictpure def compute_handle_yPos_SI_HOST_5_yKeepsTilt_guarantee(
      In_tiltEstimate: Base_Types.Integer_32,
      tiltEstimate: Base_Types.Integer_32): B =
    tiltEstimate == In_tiltEstimate

  /** Compute Entrypoint Contract for yPos's SI_HOST_17_yStrayAckIgnored guarantee clause
    *
    * guarantee SI_HOST_17_yStrayAckIgnored
    *   SI-HOST-17: A Y acknowledgement that is not awaited changes nothing and issues nothing.
    * @param In_awaitAxis pre-state state variable
    * @param In_halted pre-state state variable
    * @param In_pending pre-state state variable
    * @param In_planEnd pre-state state variable
    * @param In_planIndex pre-state state variable
    * @param awaitAxis post-state state variable
    * @param halted post-state state variable
    * @param pending post-state state variable
    * @param planEnd post-state state variable
    * @param planIndex post-state state variable
    * @param api_xCmd outgoing event data port
    * @param api_yCmd outgoing event data port
    * @param api_zCmd outgoing event data port
    */
  @strictpure def compute_handle_yPos_SI_HOST_17_yStrayAckIgnored_guarantee(
      In_awaitAxis: Base_Types.Integer_32,
      In_halted: Base_Types.Boolean,
      In_pending: Base_Types.Boolean,
      In_planEnd: Base_Types.Integer_32,
      In_planIndex: Base_Types.Integer_32,
      awaitAxis: Base_Types.Integer_32,
      halted: Base_Types.Boolean,
      pending: Base_Types.Boolean,
      planEnd: Base_Types.Integer_32,
      planIndex: Base_Types.Integer_32,
      api_xCmd: Option[std_msgs.Int32],
      api_yCmd: Option[std_msgs.Int32],
      api_zCmd: Option[std_msgs.Int32]): B =
    !(In_pending &
       In_awaitAxis == s32"2") __>:
      api_zCmd.isEmpty & api_xCmd.isEmpty &
        api_yCmd.isEmpty &
        pending == In_pending &
        awaitAxis == In_awaitAxis &
        planIndex == In_planIndex &
        planEnd == In_planEnd &
        halted == In_halted

  /** Compute Entrypoint Contract for yPos's SI_HOST_18_yAckAdvancesPlan guarantee clause
    *
    * guarantee SI_HOST_18_yAckAdvancesPlan
    *   SI-HOST-18: The awaited Y acknowledgement completes the move; the next move (if any) advances the plan by one.
    * @param In_awaitAxis pre-state state variable
    * @param In_pending pre-state state variable
    * @param In_planEnd pre-state state variable
    * @param In_planIndex pre-state state variable
    * @param pending post-state state variable
    * @param planEnd post-state state variable
    * @param planIndex post-state state variable
    * @param api_xCmd outgoing event data port
    * @param api_yCmd outgoing event data port
    * @param api_zCmd outgoing event data port
    */
  @strictpure def compute_handle_yPos_SI_HOST_18_yAckAdvancesPlan_guarantee(
      In_awaitAxis: Base_Types.Integer_32,
      In_pending: Base_Types.Boolean,
      In_planEnd: Base_Types.Integer_32,
      In_planIndex: Base_Types.Integer_32,
      pending: Base_Types.Boolean,
      planEnd: Base_Types.Integer_32,
      planIndex: Base_Types.Integer_32,
      api_xCmd: Option[std_msgs.Int32],
      api_yCmd: Option[std_msgs.Int32],
      api_zCmd: Option[std_msgs.Int32]): B =
    In_pending &
      In_awaitAxis == s32"2" __>:
      (ScanController_jetson_scan.cmdSent(api_zCmd.nonEmpty, api_xCmd.nonEmpty, api_yCmd.nonEmpty) __>:
        planIndex == In_planIndex + s32"1") &
        (!(ScanController_jetson_scan.cmdSent(api_zCmd.nonEmpty, api_xCmd.nonEmpty, api_yCmd.nonEmpty)) __>:
          !pending &
            planIndex == In_planIndex) &
        planEnd == In_planEnd

  /** CEP-T-Handle_yPos_Guar: Top-level guarantee contracts for scan's compute yPos handler
    *
    * @param In_awaitAxis pre-state state variable
    * @param In_halted pre-state state variable
    * @param In_pending pre-state state variable
    * @param In_planEnd pre-state state variable
    * @param In_planIndex pre-state state variable
    * @param In_tiltEstimate pre-state state variable
    * @param awaitAxis post-state state variable
    * @param halted post-state state variable
    * @param pending post-state state variable
    * @param planEnd post-state state variable
    * @param planIndex post-state state variable
    * @param tiltEstimate post-state state variable
    * @param api_yPos incoming event data port
    * @param api_xCmd outgoing event data port
    * @param api_yCmd outgoing event data port
    * @param api_zCmd outgoing event data port
    */
  @strictpure def compute_CEP_Handler_yPos_Guar (
      In_awaitAxis: Base_Types.Integer_32,
      In_halted: Base_Types.Boolean,
      In_pending: Base_Types.Boolean,
      In_planEnd: Base_Types.Integer_32,
      In_planIndex: Base_Types.Integer_32,
      In_tiltEstimate: Base_Types.Integer_32,
      awaitAxis: Base_Types.Integer_32,
      halted: Base_Types.Boolean,
      pending: Base_Types.Boolean,
      planEnd: Base_Types.Integer_32,
      planIndex: Base_Types.Integer_32,
      tiltEstimate: Base_Types.Integer_32,
      api_yPos: Option[std_msgs.Int32],
      api_xCmd: Option[std_msgs.Int32],
      api_yCmd: Option[std_msgs.Int32],
      api_zCmd: Option[std_msgs.Int32]): B = {
    if (api_yPos.isEmpty) {
      T
    } else
    {
      val r0 = compute_handle_yPos_SI_HOST_5_yKeepsTilt_guarantee(In_tiltEstimate, tiltEstimate)
      val r1 = compute_handle_yPos_SI_HOST_17_yStrayAckIgnored_guarantee(In_awaitAxis, In_halted, In_pending, In_planEnd, In_planIndex, awaitAxis, halted, pending, planEnd, planIndex, api_xCmd, api_yCmd, api_zCmd)
      val r2 = compute_handle_yPos_SI_HOST_18_yAckAdvancesPlan_guarantee(In_awaitAxis, In_pending, In_planEnd, In_planIndex, pending, planEnd, planIndex, api_xCmd, api_yCmd, api_zCmd)

      r0 & r1 & r2
    }
  }

  /** CEP-Post: Compute Entrypoint Post-Condition for scan
    *
    * @param In_awaitAxis pre-state state variable
    * @param In_halted pre-state state variable
    * @param In_pending pre-state state variable
    * @param In_planEnd pre-state state variable
    * @param In_planIndex pre-state state variable
    * @param In_tiltEstimate pre-state state variable
    * @param awaitAxis post-state state variable
    * @param halted post-state state variable
    * @param pending post-state state variable
    * @param planEnd post-state state variable
    * @param planIndex post-state state variable
    * @param tiltEstimate post-state state variable
    * @param api_start incoming event data port
    * @param api_xPos incoming event data port
    * @param api_yPos incoming event data port
    * @param api_zPos incoming event data port
    * @param api_xCmd outgoing event data port
    * @param api_yCmd outgoing event data port
    * @param api_zCmd outgoing event data port
    */
  @strictpure def compute_CEP_Post (
      In_awaitAxis: Base_Types.Integer_32,
      In_halted: Base_Types.Boolean,
      In_pending: Base_Types.Boolean,
      In_planEnd: Base_Types.Integer_32,
      In_planIndex: Base_Types.Integer_32,
      In_tiltEstimate: Base_Types.Integer_32,
      awaitAxis: Base_Types.Integer_32,
      halted: Base_Types.Boolean,
      pending: Base_Types.Boolean,
      planEnd: Base_Types.Integer_32,
      planIndex: Base_Types.Integer_32,
      tiltEstimate: Base_Types.Integer_32,
      api_start: Option[std_msgs.Int32],
      api_xPos: Option[std_msgs.Int32],
      api_yPos: Option[std_msgs.Int32],
      api_zPos: Option[std_msgs.Int32],
      api_xCmd: Option[std_msgs.Int32],
      api_yCmd: Option[std_msgs.Int32],
      api_zCmd: Option[std_msgs.Int32]): B =
    {
      // CEP-Guar: guarantee clauses of scan's compute entrypoint
      val r0 = compute_CEP_T_Guar (In_awaitAxis, In_halted, In_pending, awaitAxis, halted, pending, planEnd, planIndex, tiltEstimate, api_xPos, api_yPos, api_zPos, api_xCmd, api_yCmd, api_zCmd)

      // CEP-T-Handlers: handler clauses of scan's compute entrypoint
      val r1 = compute_CEP_Handler_start_Guar (In_awaitAxis, In_halted, In_pending, In_planEnd, In_planIndex, In_tiltEstimate, awaitAxis, halted, pending, planEnd, planIndex, tiltEstimate, api_start, api_xCmd, api_yCmd, api_zCmd)
      val r2 = compute_CEP_Handler_zPos_Guar (In_awaitAxis, In_halted, In_pending, In_planEnd, In_planIndex, In_tiltEstimate, awaitAxis, halted, pending, planEnd, planIndex, tiltEstimate, api_zPos, api_xCmd, api_yCmd, api_zCmd)
      val r3 = compute_CEP_Handler_xPos_Guar (In_awaitAxis, In_halted, In_pending, In_planEnd, In_planIndex, awaitAxis, halted, pending, planEnd, planIndex, tiltEstimate, api_xPos, api_xCmd, api_yCmd, api_zCmd)
      val r4 = compute_CEP_Handler_yPos_Guar (In_awaitAxis, In_halted, In_pending, In_planEnd, In_planIndex, In_tiltEstimate, awaitAxis, halted, pending, planEnd, planIndex, tiltEstimate, api_yPos, api_xCmd, api_yCmd, api_zCmd)

      r0 & r1 & r2 & r3 & r4
    }

  /** CEP-Post: Compute Entrypoint Post-Condition for scan via containers
    *
    * @param pre Container holding the values of incoming ports and the pre-state values of state variables
    * @param post Container holding the values of outgoing ports and the post-state values of state variables
    */
  @strictpure def compute_CEP_Post_Container(
      pre: ScanController_jetson_scan_PreState_Container_PS,
      post: ScanController_jetson_scan_PostState_Container_PS): B =
    compute_CEP_Post(
      In_awaitAxis = pre.In_awaitAxis,
      In_halted = pre.In_halted,
      In_pending = pre.In_pending,
      In_planEnd = pre.In_planEnd,
      In_planIndex = pre.In_planIndex,
      In_tiltEstimate = pre.In_tiltEstimate,
      awaitAxis = post.awaitAxis,
      halted = post.halted,
      pending = post.pending,
      planEnd = post.planEnd,
      planIndex = post.planIndex,
      tiltEstimate = post.tiltEstimate,
      api_start = pre.api_start,
      api_xPos = pre.api_xPos,
      api_yPos = pre.api_yPos,
      api_zPos = pre.api_zPos,
      api_xCmd = post.api_xCmd,
      api_yCmd = post.api_yCmd,
      api_zCmd = post.api_zCmd)
}
