// #Sireum

package seedimaging.SeedImaging

import org.sireum._
import seedimaging._
import org.sireum.S32._

// Do not edit this file as it will be overwritten if HAMR codegen is rerun
object StepperController_esp32_stepper_GumboX {
  /** I-Guar: Integration constraint on stepper's outgoing event data port xPos
    *
    * guarantee SI_MCU_16_tiltAckInRange
    *   SI-MCU-16: Every published tilt position lies within +/-45 deg.
    */
  @strictpure def I_Guar_xPos(xPos: std_msgs.Int32): B =
    SeedImaging.GUMBO__Library.isTiltSafe(xPos.data)

  // I_Guar-Guard: Integration constraint on stepper's outgoing event data port xPos
  @strictpure def I_Guar_Guard_xPos(xPos: Option[std_msgs.Int32]): B =
    xPos.nonEmpty ___>: I_Guar_xPos(xPos.get)

  /** Initialize Entrypoint Contract
    *
    * guarantee SI_MCU_1_homeAtStartup
    *   SI-MCU-1: At power-up all three axes are taken to be at home (0 steps).
    * @param xPosition post-state state variable
    * @param yPosition post-state state variable
    * @param zPosition post-state state variable
    */
  @strictpure def initialize_SI_MCU_1_homeAtStartup (
      xPosition: Base_Types.Integer_32,
      yPosition: Base_Types.Integer_32,
      zPosition: Base_Types.Integer_32): B =
    zPosition == s32"0" &
      xPosition == s32"0" &
      yPosition == s32"0"

  /** IEP-Guar: Initialize Entrypoint Contracts for stepper
    *
    * @param xPosition post-state state variable
    * @param yPosition post-state state variable
    * @param zPosition post-state state variable
    * @param api_xPos outgoing event data port
    * @param api_yPos outgoing event data port
    * @param api_zPos outgoing event data port
    */
  @strictpure def initialize_IEP_Guar (
      xPosition: Base_Types.Integer_32,
      yPosition: Base_Types.Integer_32,
      zPosition: Base_Types.Integer_32,
      api_xPos: Option[std_msgs.Int32],
      api_yPos: Option[std_msgs.Int32],
      api_zPos: Option[std_msgs.Int32]): B =
    initialize_SI_MCU_1_homeAtStartup(xPosition, yPosition, zPosition)

  /** IEP-Post: Initialize Entrypoint Post-Condition
    *
    * @param xPosition post-state state variable
    * @param yPosition post-state state variable
    * @param zPosition post-state state variable
    * @param api_xPos outgoing event data port
    * @param api_yPos outgoing event data port
    * @param api_zPos outgoing event data port
    */
  @strictpure def inititialize_IEP_Post (
      xPosition: Base_Types.Integer_32,
      yPosition: Base_Types.Integer_32,
      zPosition: Base_Types.Integer_32,
      api_xPos: Option[std_msgs.Int32],
      api_yPos: Option[std_msgs.Int32],
      api_zPos: Option[std_msgs.Int32]): B =
    {
      // I-Guar-Guard: Integration constraints for stepper's outgoing ports
      val r0 = I_Guar_Guard_xPos(api_xPos)

      // IEP-Guar: Initialize Entrypoint contract for stepper
      val r1 = initialize_IEP_Guar(xPosition, yPosition, zPosition, api_xPos, api_yPos, api_zPos)

      r0 & r1
    }

  /** IEP-Post: Initialize Entrypoint Post-Condition via container
    *
    * @param post Container holding the value of incoming ports and the pre-state values of state variables
    */
  @strictpure def inititialize_IEP_Post_Container (post: StepperController_esp32_stepper_PostState_Container_PS): B =
    inititialize_IEP_Post (
      xPosition = post.xPosition,
      yPosition = post.yPosition,
      zPosition = post.zPosition,
      api_xPos = post.api_xPos,
      api_yPos = post.api_yPos,
      api_zPos = post.api_zPos)

  /** Compute Entrypoint Contract
    *
    * assume SI_MCU_A1_positionsInRange
    *   Positions are within their ranges when a command arrives.
    * @param In_xPosition pre-state state variable
    * @param In_yPosition pre-state state variable
    * @param In_zPosition pre-state state variable
    */
  @strictpure def compute_spec_SI_MCU_A1_positionsInRange_assume(
      In_xPosition: Base_Types.Integer_32,
      In_yPosition: Base_Types.Integer_32,
      In_zPosition: Base_Types.Integer_32): B =
    SeedImaging.GUMBO__Library.isRotaryIndex(In_zPosition) & SeedImaging.GUMBO__Library.isTiltSafe(In_xPosition) &
      SeedImaging.GUMBO__Library.isRotaryIndex(In_yPosition)

  /** CEP-T-Assm: Top-level assume contracts for stepper's compute entrypoint
    *
    * @param In_xPosition pre-state state variable
    * @param In_yPosition pre-state state variable
    * @param In_zPosition pre-state state variable
    */
  @strictpure def compute_CEP_T_Assm (
      In_xPosition: Base_Types.Integer_32,
      In_yPosition: Base_Types.Integer_32,
      In_zPosition: Base_Types.Integer_32): B =
    compute_spec_SI_MCU_A1_positionsInRange_assume(In_xPosition, In_yPosition, In_zPosition)

  /** CEP-Pre: Compute Entrypoint Pre-Condition for stepper
    *
    * @param In_xPosition pre-state state variable
    * @param In_yPosition pre-state state variable
    * @param In_zPosition pre-state state variable
    * @param api_xCmd incoming event data port
    * @param api_yCmd incoming event data port
    * @param api_zCmd incoming event data port
    */
  @strictpure def compute_CEP_Pre (
      In_xPosition: Base_Types.Integer_32,
      In_yPosition: Base_Types.Integer_32,
      In_zPosition: Base_Types.Integer_32,
      api_xCmd: Option[std_msgs.Int32],
      api_yCmd: Option[std_msgs.Int32],
      api_zCmd: Option[std_msgs.Int32]): B =
    {
      // CEP-Assm: assume clauses of stepper's compute entrypoint
      compute_CEP_T_Assm (In_xPosition, In_yPosition, In_zPosition)
    }

  /** CEP-Pre: Compute Entrypoint Pre-Condition for stepper via container
    *
    * @param pre Container holding the value of incoming ports and the pre-state values of state variables
    */
  @strictpure def compute_CEP_Pre_Container(pre: StepperController_esp32_stepper_PreState_Container_PS): B =
    compute_CEP_Pre(
      In_xPosition = pre.In_xPosition,
      In_yPosition = pre.In_yPosition,
      In_zPosition = pre.In_zPosition,
      api_xCmd = pre.api_xCmd,
      api_yCmd = pre.api_yCmd,
      api_zCmd = pre.api_zCmd)

  /** Compute Entrypoint Contract
    *
    * guarantee SI_MCU_2_tiltNeverBeyond45
    *   SI-MCU-2: The tilt axis never leaves +/-45 deg (+/-25 steps).
    * @param xPosition post-state state variable
    */
  @strictpure def compute_spec_SI_MCU_2_tiltNeverBeyond45_guarantee(
      xPosition: Base_Types.Integer_32): B =
    SeedImaging.GUMBO__Library.isTiltSafe(xPosition)

  /** Compute Entrypoint Contract
    *
    * guarantee SI_MCU_3_rotaryModuloOneRev
    *   SI-MCU-3: Turntable and Y positions are kept modulo one revolution.
    * @param yPosition post-state state variable
    * @param zPosition post-state state variable
    */
  @strictpure def compute_spec_SI_MCU_3_rotaryModuloOneRev_guarantee(
      yPosition: Base_Types.Integer_32,
      zPosition: Base_Types.Integer_32): B =
    SeedImaging.GUMBO__Library.isRotaryIndex(zPosition) & SeedImaging.GUMBO__Library.isRotaryIndex(yPosition)

  /** CEP-T-Guar: Top-level guarantee contracts for stepper's compute entrypoint
    *
    * @param xPosition post-state state variable
    * @param yPosition post-state state variable
    * @param zPosition post-state state variable
    */
  @strictpure def compute_CEP_T_Guar (
      xPosition: Base_Types.Integer_32,
      yPosition: Base_Types.Integer_32,
      zPosition: Base_Types.Integer_32): B =
    {
      val r0 = compute_spec_SI_MCU_2_tiltNeverBeyond45_guarantee(xPosition)
      val r1 = compute_spec_SI_MCU_3_rotaryModuloOneRev_guarantee(yPosition, zPosition)

      r0 & r1
    }

  /** Compute Entrypoint Contract for zCmd's SI_MCU_4_zExactMove guarantee clause
    *
    * guarantee SI_MCU_4_zExactMove
    *   SI-MCU-4: A bounded turntable command rotates the turntable by exactly the commanded steps.
    * @param In_zPosition pre-state state variable
    * @param zPosition post-state state variable
    * @param api_zCmd incoming event data port
    */
  @strictpure def compute_handle_zCmd_SI_MCU_4_zExactMove_guarantee(
      In_zPosition: Base_Types.Integer_32,
      zPosition: Base_Types.Integer_32,
      api_zCmd: Option[std_msgs.Int32]): B =
    SeedImaging.GUMBO__Library.isBoundedMove(api_zCmd.get.data) __>:
      zPosition == SeedImaging.GUMBO__Library.wrapRotary(In_zPosition + api_zCmd.get.data)

  /** Compute Entrypoint Contract for zCmd's SI_MCU_5_zRejectOversize guarantee clause
    *
    * guarantee SI_MCU_5_zRejectOversize
    *   SI-MCU-5: An oversize turntable command is rejected: no motion.
    * @param In_zPosition pre-state state variable
    * @param zPosition post-state state variable
    * @param api_zCmd incoming event data port
    */
  @strictpure def compute_handle_zCmd_SI_MCU_5_zRejectOversize_guarantee(
      In_zPosition: Base_Types.Integer_32,
      zPosition: Base_Types.Integer_32,
      api_zCmd: Option[std_msgs.Int32]): B =
    !(SeedImaging.GUMBO__Library.isBoundedMove(api_zCmd.get.data)) __>:
      zPosition == In_zPosition

  /** Compute Entrypoint Contract for zCmd's SI_MCU_6_zAxisIsolation guarantee clause
    *
    * guarantee SI_MCU_6_zAxisIsolation
    *   SI-MCU-6: A turntable command never moves the tilt or Y axis.
    * @param In_xPosition pre-state state variable
    * @param In_yPosition pre-state state variable
    * @param xPosition post-state state variable
    * @param yPosition post-state state variable
    */
  @strictpure def compute_handle_zCmd_SI_MCU_6_zAxisIsolation_guarantee(
      In_xPosition: Base_Types.Integer_32,
      In_yPosition: Base_Types.Integer_32,
      xPosition: Base_Types.Integer_32,
      yPosition: Base_Types.Integer_32): B =
    xPosition == In_xPosition &
      yPosition == In_yPosition

  /** Compute Entrypoint Contract for zCmd's SI_MCU_7_zAcknowledged guarantee clause
    *
    * guarantee SI_MCU_7_zAcknowledged
    *   SI-MCU-7: Every turntable command is acknowledged once, on zPos only, with the new turntable position.
    * @param zPosition post-state state variable
    * @param api_xPos outgoing event data port
    * @param api_yPos outgoing event data port
    * @param api_zPos outgoing event data port
    */
  @strictpure def compute_handle_zCmd_SI_MCU_7_zAcknowledged_guarantee(
      zPosition: Base_Types.Integer_32,
      api_xPos: Option[std_msgs.Int32],
      api_yPos: Option[std_msgs.Int32],
      api_zPos: Option[std_msgs.Int32]): B =
    api_zPos.nonEmpty &&
      api_zPos.get.data == zPosition &
      api_xPos.isEmpty &
      api_yPos.isEmpty

  /** CEP-T-Handle_zCmd_Guar: Top-level guarantee contracts for stepper's compute zCmd handler
    *
    * @param In_xPosition pre-state state variable
    * @param In_yPosition pre-state state variable
    * @param In_zPosition pre-state state variable
    * @param xPosition post-state state variable
    * @param yPosition post-state state variable
    * @param zPosition post-state state variable
    * @param api_zCmd incoming event data port
    * @param api_xPos outgoing event data port
    * @param api_yPos outgoing event data port
    * @param api_zPos outgoing event data port
    */
  @strictpure def compute_CEP_Handler_zCmd_Guar (
      In_xPosition: Base_Types.Integer_32,
      In_yPosition: Base_Types.Integer_32,
      In_zPosition: Base_Types.Integer_32,
      xPosition: Base_Types.Integer_32,
      yPosition: Base_Types.Integer_32,
      zPosition: Base_Types.Integer_32,
      api_zCmd: Option[std_msgs.Int32],
      api_xPos: Option[std_msgs.Int32],
      api_yPos: Option[std_msgs.Int32],
      api_zPos: Option[std_msgs.Int32]): B = {
    if (api_zCmd.isEmpty) {
      T
    } else
    {
      val r0 = compute_handle_zCmd_SI_MCU_4_zExactMove_guarantee(In_zPosition, zPosition, api_zCmd)
      val r1 = compute_handle_zCmd_SI_MCU_5_zRejectOversize_guarantee(In_zPosition, zPosition, api_zCmd)
      val r2 = compute_handle_zCmd_SI_MCU_6_zAxisIsolation_guarantee(In_xPosition, In_yPosition, xPosition, yPosition)
      val r3 = compute_handle_zCmd_SI_MCU_7_zAcknowledged_guarantee(zPosition, api_xPos, api_yPos, api_zPos)

      r0 & r1 & r2 & r3
    }
  }

  /** Compute Entrypoint Contract for xCmd's SI_MCU_8_xExactMove guarantee clause
    *
    * guarantee SI_MCU_8_xExactMove
    *   SI-MCU-8: A tilt command that is bounded and lands within +/-45 deg moves the tilt by exactly the commanded steps.
    * @param In_xPosition pre-state state variable
    * @param xPosition post-state state variable
    * @param api_xCmd incoming event data port
    */
  @strictpure def compute_handle_xCmd_SI_MCU_8_xExactMove_guarantee(
      In_xPosition: Base_Types.Integer_32,
      xPosition: Base_Types.Integer_32,
      api_xCmd: Option[std_msgs.Int32]): B =
    SeedImaging.GUMBO__Library.isSafeTiltMove(In_xPosition, api_xCmd.get.data) __>:
      xPosition == In_xPosition + api_xCmd.get.data

  /** Compute Entrypoint Contract for xCmd's SI_MCU_9_xRejectUnsafe guarantee clause
    *
    * guarantee SI_MCU_9_xRejectUnsafe
    *   SI-MCU-9: A tilt command that is oversize or would leave +/-45 deg is rejected: no motion.
    * @param In_xPosition pre-state state variable
    * @param xPosition post-state state variable
    * @param api_xCmd incoming event data port
    */
  @strictpure def compute_handle_xCmd_SI_MCU_9_xRejectUnsafe_guarantee(
      In_xPosition: Base_Types.Integer_32,
      xPosition: Base_Types.Integer_32,
      api_xCmd: Option[std_msgs.Int32]): B =
    !(SeedImaging.GUMBO__Library.isSafeTiltMove(In_xPosition, api_xCmd.get.data)) __>:
      xPosition == In_xPosition

  /** Compute Entrypoint Contract for xCmd's SI_MCU_10_xAxisIsolation guarantee clause
    *
    * guarantee SI_MCU_10_xAxisIsolation
    *   SI-MCU-10: A tilt command never moves the turntable or Y axis.
    * @param In_yPosition pre-state state variable
    * @param In_zPosition pre-state state variable
    * @param yPosition post-state state variable
    * @param zPosition post-state state variable
    */
  @strictpure def compute_handle_xCmd_SI_MCU_10_xAxisIsolation_guarantee(
      In_yPosition: Base_Types.Integer_32,
      In_zPosition: Base_Types.Integer_32,
      yPosition: Base_Types.Integer_32,
      zPosition: Base_Types.Integer_32): B =
    zPosition == In_zPosition &
      yPosition == In_yPosition

  /** Compute Entrypoint Contract for xCmd's SI_MCU_11_xAcknowledged guarantee clause
    *
    * guarantee SI_MCU_11_xAcknowledged
    *   SI-MCU-11: Every tilt command is acknowledged once, on xPos only, with the new tilt position.
    * @param xPosition post-state state variable
    * @param api_xPos outgoing event data port
    * @param api_yPos outgoing event data port
    * @param api_zPos outgoing event data port
    */
  @strictpure def compute_handle_xCmd_SI_MCU_11_xAcknowledged_guarantee(
      xPosition: Base_Types.Integer_32,
      api_xPos: Option[std_msgs.Int32],
      api_yPos: Option[std_msgs.Int32],
      api_zPos: Option[std_msgs.Int32]): B =
    api_xPos.nonEmpty &&
      api_xPos.get.data == xPosition &
      api_zPos.isEmpty &
      api_yPos.isEmpty

  /** CEP-T-Handle_xCmd_Guar: Top-level guarantee contracts for stepper's compute xCmd handler
    *
    * @param In_xPosition pre-state state variable
    * @param In_yPosition pre-state state variable
    * @param In_zPosition pre-state state variable
    * @param xPosition post-state state variable
    * @param yPosition post-state state variable
    * @param zPosition post-state state variable
    * @param api_xCmd incoming event data port
    * @param api_xPos outgoing event data port
    * @param api_yPos outgoing event data port
    * @param api_zPos outgoing event data port
    */
  @strictpure def compute_CEP_Handler_xCmd_Guar (
      In_xPosition: Base_Types.Integer_32,
      In_yPosition: Base_Types.Integer_32,
      In_zPosition: Base_Types.Integer_32,
      xPosition: Base_Types.Integer_32,
      yPosition: Base_Types.Integer_32,
      zPosition: Base_Types.Integer_32,
      api_xCmd: Option[std_msgs.Int32],
      api_xPos: Option[std_msgs.Int32],
      api_yPos: Option[std_msgs.Int32],
      api_zPos: Option[std_msgs.Int32]): B = {
    if (api_xCmd.isEmpty) {
      T
    } else
    {
      val r0 = compute_handle_xCmd_SI_MCU_8_xExactMove_guarantee(In_xPosition, xPosition, api_xCmd)
      val r1 = compute_handle_xCmd_SI_MCU_9_xRejectUnsafe_guarantee(In_xPosition, xPosition, api_xCmd)
      val r2 = compute_handle_xCmd_SI_MCU_10_xAxisIsolation_guarantee(In_yPosition, In_zPosition, yPosition, zPosition)
      val r3 = compute_handle_xCmd_SI_MCU_11_xAcknowledged_guarantee(xPosition, api_xPos, api_yPos, api_zPos)

      r0 & r1 & r2 & r3
    }
  }

  /** Compute Entrypoint Contract for yCmd's SI_MCU_12_yExactMove guarantee clause
    *
    * guarantee SI_MCU_12_yExactMove
    *   SI-MCU-12: A bounded Y command rotates the Y axis by exactly the commanded steps.
    * @param In_yPosition pre-state state variable
    * @param yPosition post-state state variable
    * @param api_yCmd incoming event data port
    */
  @strictpure def compute_handle_yCmd_SI_MCU_12_yExactMove_guarantee(
      In_yPosition: Base_Types.Integer_32,
      yPosition: Base_Types.Integer_32,
      api_yCmd: Option[std_msgs.Int32]): B =
    SeedImaging.GUMBO__Library.isBoundedMove(api_yCmd.get.data) __>:
      yPosition == SeedImaging.GUMBO__Library.wrapRotary(In_yPosition + api_yCmd.get.data)

  /** Compute Entrypoint Contract for yCmd's SI_MCU_13_yRejectOversize guarantee clause
    *
    * guarantee SI_MCU_13_yRejectOversize
    *   SI-MCU-13: An oversize Y command is rejected: no motion.
    * @param In_yPosition pre-state state variable
    * @param yPosition post-state state variable
    * @param api_yCmd incoming event data port
    */
  @strictpure def compute_handle_yCmd_SI_MCU_13_yRejectOversize_guarantee(
      In_yPosition: Base_Types.Integer_32,
      yPosition: Base_Types.Integer_32,
      api_yCmd: Option[std_msgs.Int32]): B =
    !(SeedImaging.GUMBO__Library.isBoundedMove(api_yCmd.get.data)) __>:
      yPosition == In_yPosition

  /** Compute Entrypoint Contract for yCmd's SI_MCU_14_yAxisIsolation guarantee clause
    *
    * guarantee SI_MCU_14_yAxisIsolation
    *   SI-MCU-14: A Y command never moves the turntable or tilt axis.
    * @param In_xPosition pre-state state variable
    * @param In_zPosition pre-state state variable
    * @param xPosition post-state state variable
    * @param zPosition post-state state variable
    */
  @strictpure def compute_handle_yCmd_SI_MCU_14_yAxisIsolation_guarantee(
      In_xPosition: Base_Types.Integer_32,
      In_zPosition: Base_Types.Integer_32,
      xPosition: Base_Types.Integer_32,
      zPosition: Base_Types.Integer_32): B =
    zPosition == In_zPosition &
      xPosition == In_xPosition

  /** Compute Entrypoint Contract for yCmd's SI_MCU_15_yAcknowledged guarantee clause
    *
    * guarantee SI_MCU_15_yAcknowledged
    *   SI-MCU-15: Every Y command is acknowledged once, on yPos only, with the new Y position.
    * @param yPosition post-state state variable
    * @param api_xPos outgoing event data port
    * @param api_yPos outgoing event data port
    * @param api_zPos outgoing event data port
    */
  @strictpure def compute_handle_yCmd_SI_MCU_15_yAcknowledged_guarantee(
      yPosition: Base_Types.Integer_32,
      api_xPos: Option[std_msgs.Int32],
      api_yPos: Option[std_msgs.Int32],
      api_zPos: Option[std_msgs.Int32]): B =
    api_yPos.nonEmpty &&
      api_yPos.get.data == yPosition &
      api_zPos.isEmpty &
      api_xPos.isEmpty

  /** CEP-T-Handle_yCmd_Guar: Top-level guarantee contracts for stepper's compute yCmd handler
    *
    * @param In_xPosition pre-state state variable
    * @param In_yPosition pre-state state variable
    * @param In_zPosition pre-state state variable
    * @param xPosition post-state state variable
    * @param yPosition post-state state variable
    * @param zPosition post-state state variable
    * @param api_yCmd incoming event data port
    * @param api_xPos outgoing event data port
    * @param api_yPos outgoing event data port
    * @param api_zPos outgoing event data port
    */
  @strictpure def compute_CEP_Handler_yCmd_Guar (
      In_xPosition: Base_Types.Integer_32,
      In_yPosition: Base_Types.Integer_32,
      In_zPosition: Base_Types.Integer_32,
      xPosition: Base_Types.Integer_32,
      yPosition: Base_Types.Integer_32,
      zPosition: Base_Types.Integer_32,
      api_yCmd: Option[std_msgs.Int32],
      api_xPos: Option[std_msgs.Int32],
      api_yPos: Option[std_msgs.Int32],
      api_zPos: Option[std_msgs.Int32]): B = {
    if (api_yCmd.isEmpty) {
      T
    } else
    {
      val r0 = compute_handle_yCmd_SI_MCU_12_yExactMove_guarantee(In_yPosition, yPosition, api_yCmd)
      val r1 = compute_handle_yCmd_SI_MCU_13_yRejectOversize_guarantee(In_yPosition, yPosition, api_yCmd)
      val r2 = compute_handle_yCmd_SI_MCU_14_yAxisIsolation_guarantee(In_xPosition, In_zPosition, xPosition, zPosition)
      val r3 = compute_handle_yCmd_SI_MCU_15_yAcknowledged_guarantee(yPosition, api_xPos, api_yPos, api_zPos)

      r0 & r1 & r2 & r3
    }
  }

  /** CEP-Post: Compute Entrypoint Post-Condition for stepper
    *
    * @param In_xPosition pre-state state variable
    * @param In_yPosition pre-state state variable
    * @param In_zPosition pre-state state variable
    * @param xPosition post-state state variable
    * @param yPosition post-state state variable
    * @param zPosition post-state state variable
    * @param api_xCmd incoming event data port
    * @param api_yCmd incoming event data port
    * @param api_zCmd incoming event data port
    * @param api_xPos outgoing event data port
    * @param api_yPos outgoing event data port
    * @param api_zPos outgoing event data port
    */
  @strictpure def compute_CEP_Post (
      In_xPosition: Base_Types.Integer_32,
      In_yPosition: Base_Types.Integer_32,
      In_zPosition: Base_Types.Integer_32,
      xPosition: Base_Types.Integer_32,
      yPosition: Base_Types.Integer_32,
      zPosition: Base_Types.Integer_32,
      api_xCmd: Option[std_msgs.Int32],
      api_yCmd: Option[std_msgs.Int32],
      api_zCmd: Option[std_msgs.Int32],
      api_xPos: Option[std_msgs.Int32],
      api_yPos: Option[std_msgs.Int32],
      api_zPos: Option[std_msgs.Int32]): B =
    {
      // I-Guar-Guard: Integration constraints for stepper's outgoing ports
      val r0 = I_Guar_Guard_xPos(api_xPos)

      // CEP-Guar: guarantee clauses of stepper's compute entrypoint
      val r1 = compute_CEP_T_Guar (xPosition, yPosition, zPosition)

      // CEP-T-Handlers: handler clauses of stepper's compute entrypoint
      val r2 = compute_CEP_Handler_zCmd_Guar (In_xPosition, In_yPosition, In_zPosition, xPosition, yPosition, zPosition, api_zCmd, api_xPos, api_yPos, api_zPos)
      val r3 = compute_CEP_Handler_xCmd_Guar (In_xPosition, In_yPosition, In_zPosition, xPosition, yPosition, zPosition, api_xCmd, api_xPos, api_yPos, api_zPos)
      val r4 = compute_CEP_Handler_yCmd_Guar (In_xPosition, In_yPosition, In_zPosition, xPosition, yPosition, zPosition, api_yCmd, api_xPos, api_yPos, api_zPos)

      r0 & r1 & r2 & r3 & r4
    }

  /** CEP-Post: Compute Entrypoint Post-Condition for stepper via containers
    *
    * @param pre Container holding the values of incoming ports and the pre-state values of state variables
    * @param post Container holding the values of outgoing ports and the post-state values of state variables
    */
  @strictpure def compute_CEP_Post_Container(
      pre: StepperController_esp32_stepper_PreState_Container_PS,
      post: StepperController_esp32_stepper_PostState_Container_PS): B =
    compute_CEP_Post(
      In_xPosition = pre.In_xPosition,
      In_yPosition = pre.In_yPosition,
      In_zPosition = pre.In_zPosition,
      xPosition = post.xPosition,
      yPosition = post.yPosition,
      zPosition = post.zPosition,
      api_xCmd = pre.api_xCmd,
      api_yCmd = pre.api_yCmd,
      api_zCmd = pre.api_zCmd,
      api_xPos = post.api_xPos,
      api_yPos = post.api_yPos,
      api_zPos = post.api_zPos)
}
