// #Sireum

package seedimaging.SeedImaging

import org.sireum._
import art._
import seedimaging._
import seedimaging.SeedImaging.{StepperController_esp32_stepper => component}

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

@datatype class StepperController_esp32_stepper_Bridge(
  val id: Art.BridgeId,
  val name: String,
  val dispatchProtocol: DispatchPropertyProtocol,
  val dispatchTriggers: Option[ISZ[Art.PortId]],

  zCmd: Port[std_msgs.Int32],
  xCmd: Port[std_msgs.Int32],
  yCmd: Port[std_msgs.Int32],
  zPos: Port[std_msgs.Int32],
  xPos: Port[std_msgs.Int32],
  yPos: Port[std_msgs.Int32]
  ) extends Bridge {

  val ports : Bridge.Ports = Bridge.Ports(
    dataIns = ISZ[art.UPort](),

    dataOuts = ISZ[art.UPort](),

    eventIns = ISZ[art.UPort](zCmd,
                              xCmd,
                              yCmd),

    eventOuts = ISZ[art.UPort](zPos,
                               xPos,
                               yPos)
  )

  val initialization_api : StepperController_Initialization_Api = {
    val api = StepperController_Initialization_Api(
      id,
      zCmd.id,
      xCmd.id,
      yCmd.id,
      zPos.id,
      xPos.id,
      yPos.id
    )
    StepperController_esp32_stepper_Bridge.c_initialization_api = Some(api)
    api
  }

  val operational_api : StepperController_Operational_Api = {
    val api = StepperController_Operational_Api(
      id,
      zCmd.id,
      xCmd.id,
      yCmd.id,
      zPos.id,
      xPos.id,
      yPos.id
    )
    StepperController_esp32_stepper_Bridge.c_operational_api = Some(api)
    api
  }

  val entryPoints : Bridge.EntryPoints =
    StepperController_esp32_stepper_Bridge.EntryPoints(
      id,

      zCmd.id,
      xCmd.id,
      yCmd.id,
      zPos.id,
      xPos.id,
      yPos.id,

      dispatchTriggers,

      initialization_api,
      operational_api)
}

object StepperController_esp32_stepper_Bridge {

  var c_initialization_api: Option[StepperController_Initialization_Api] = None()
  var c_operational_api: Option[StepperController_Operational_Api] = None()

  @datatype class EntryPoints(
    StepperController_esp32_stepper_BridgeId : Art.BridgeId,
    zCmd_Id : Art.PortId,
    xCmd_Id : Art.PortId,
    yCmd_Id : Art.PortId,
    zPos_Id : Art.PortId,
    xPos_Id : Art.PortId,
    yPos_Id : Art.PortId,
    dispatchTriggers : Option[ISZ[Art.PortId]],
    initialization_api: StepperController_Initialization_Api,
    operational_api: StepperController_Operational_Api) extends Bridge.EntryPoints {

    val dataInPortIds: ISZ[Art.PortId] = IS()

    val eventInPortIds: ISZ[Art.PortId] = IS(zCmd_Id,
                                             xCmd_Id,
                                             yCmd_Id)

    val dataOutPortIds: ISZ[Art.PortId] = IS()

    val eventOutPortIds: ISZ[Art.PortId] = IS(zPos_Id,
                                              xPos_Id,
                                              yPos_Id)

    def initialise(): Unit = {
      // implement the following method in 'component':  def initialise(api: StepperController_Initialization_Api): Unit = {}
      component.initialise(initialization_api)
      Art.sendOutput(eventOutPortIds, dataOutPortIds)
    }

    def compute(): Unit = {
      // transpiler friendly filter
      def filter(receivedEvents: ISZ[Art.PortId], triggers: ISZ[Art.PortId]): ISZ[Art.PortId] = {
        var r = ISZ[Art.PortId]()
        val opsTriggers = ops.ISZOps(triggers)
        for(e <- receivedEvents) {
          if(opsTriggers.contains(e)) {
            r = r :+ e
          }
        }
        return r
      }

      // fetch received events ordered by highest urgency then earliest arrival-time
      val EventTriggered(receivedEvents) = Art.dispatchStatus(StepperController_esp32_stepper_BridgeId)

      // remove non-dispatching event ports
      val dispatchableEventPorts: ISZ[Art.PortId] =
        if(dispatchTriggers.isEmpty) receivedEvents
        else filter(receivedEvents, dispatchTriggers.get)

      Art.receiveInput(eventInPortIds, dataInPortIds)

      for(portId <- dispatchableEventPorts) {
        if(portId == zCmd_Id){
          val Some(std_msgs.Int32_Payload(value)) = Art.getValue(zCmd_Id)

          // implement the following in 'component':  def handle_zCmd(api: StepperController_Operational_Api, value: std_msgs.Int32): Unit = {}
          component.handle_zCmd(operational_api, value)
        }
        else if(portId == xCmd_Id){
          val Some(std_msgs.Int32_Payload(value)) = Art.getValue(xCmd_Id)

          // implement the following in 'component':  def handle_xCmd(api: StepperController_Operational_Api, value: std_msgs.Int32): Unit = {}
          component.handle_xCmd(operational_api, value)
        }
        else if(portId == yCmd_Id){
          val Some(std_msgs.Int32_Payload(value)) = Art.getValue(yCmd_Id)

          // implement the following in 'component':  def handle_yCmd(api: StepperController_Operational_Api, value: std_msgs.Int32): Unit = {}
          component.handle_yCmd(operational_api, value)
        }
      }

      Art.sendOutput(eventOutPortIds, dataOutPortIds)
    }

    def finalise(): Unit = {
      // implement the following method in 'component':  def finalise(api: StepperController_Operational_Api): Unit = {}
      component.finalise(operational_api)
    }

    override
    def testInitialise(): Unit = {
      // implement the following method in 'component':  def initialise(api: StepperController_Initialization_Api): Unit = {}
      component.initialise(initialization_api)
      Art.releaseOutput(eventOutPortIds, dataOutPortIds)
    }

    override
    def testCompute(): Unit = {
      // transpiler friendly filter
      def filter(receivedEvents: ISZ[Art.PortId], triggers: ISZ[Art.PortId]): ISZ[Art.PortId] = {
        var r = ISZ[Art.PortId]()
        val opsTriggers = ops.ISZOps(triggers)
        for(e <- receivedEvents) {
          if(opsTriggers.contains(e)) {
            r = r :+ e
          }
        }
        return r
      }

      // fetch received events ordered by highest urgency then earliest arrival-time
      val EventTriggered(receivedEvents) = Art.dispatchStatus(StepperController_esp32_stepper_BridgeId)

      // remove non-dispatching event ports
      val dispatchableEventPorts: ISZ[Art.PortId] =
        if(dispatchTriggers.isEmpty) receivedEvents
        else filter(receivedEvents, dispatchTriggers.get)

      Art.receiveInput(eventInPortIds, dataInPortIds)

      for(portId <- dispatchableEventPorts) {
        if(portId == zCmd_Id){
          val Some(std_msgs.Int32_Payload(value)) = Art.getValue(zCmd_Id)

          // implement the following in 'component':  def handle_zCmd(api: StepperController_Operational_Api, value: std_msgs.Int32): Unit = {}
          component.handle_zCmd(operational_api, value)
        }
        else if(portId == xCmd_Id){
          val Some(std_msgs.Int32_Payload(value)) = Art.getValue(xCmd_Id)

          // implement the following in 'component':  def handle_xCmd(api: StepperController_Operational_Api, value: std_msgs.Int32): Unit = {}
          component.handle_xCmd(operational_api, value)
        }
        else if(portId == yCmd_Id){
          val Some(std_msgs.Int32_Payload(value)) = Art.getValue(yCmd_Id)

          // implement the following in 'component':  def handle_yCmd(api: StepperController_Operational_Api, value: std_msgs.Int32): Unit = {}
          component.handle_yCmd(operational_api, value)
        }
      }

      Art.releaseOutput(eventOutPortIds, dataOutPortIds)
    }
  }
}