// #Sireum

package seedimaging.SeedImaging

import org.sireum._
import art._
import seedimaging._

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

object StepperController_Api {
  // guarantee SI_MCU_16_tiltAckInRange
  //   SI-MCU-16: Every published tilt position lies within +/-45 deg.
  @strictpure def SI_MCU_16_tiltAckInRange(xPos: std_msgs.Int32): B =
    SeedImaging.GUMBO__Library.isTiltSafe(xPos.data)
}

import StepperController_Api._

@sig trait StepperController_Api {
  def id: Art.BridgeId
  def zCmd_Id : Art.PortId
  def xCmd_Id : Art.PortId
  def yCmd_Id : Art.PortId
  def zPos_Id : Art.PortId
  def xPos_Id : Art.PortId
  def yPos_Id : Art.PortId

  // Logika spec var representing port state for outgoing event data port
  @spec var zPos: Option[std_msgs.Int32] = $

  def put_zPos(value : std_msgs.Int32) : Unit = {
    Contract(
      Modifies(zPos),
      Ensures(
        zPos == Some(value)
      )
    )
    Spec {
      zPos = Some(value)
    }

    Art.putValue(zPos_Id, std_msgs.Int32_Payload(value))
  }

  // Logika spec var representing port state for outgoing event data port
  @spec var xPos: Option[std_msgs.Int32] = $
  @spec def xPos_Inv = Invariant(
    xPos.isEmpty || SI_MCU_16_tiltAckInRange(xPos.get)
  )

  def put_xPos(value : std_msgs.Int32) : Unit = {
    Contract(
      Requires(
        SI_MCU_16_tiltAckInRange(value)
      ),
      Modifies(xPos),
      Ensures(
        xPos == Some(value)
      )
    )
    Spec {
      xPos = Some(value)
    }

    Art.putValue(xPos_Id, std_msgs.Int32_Payload(value))
  }

  // Logika spec var representing port state for outgoing event data port
  @spec var yPos: Option[std_msgs.Int32] = $

  def put_yPos(value : std_msgs.Int32) : Unit = {
    Contract(
      Modifies(yPos),
      Ensures(
        yPos == Some(value)
      )
    )
    Spec {
      yPos = Some(value)
    }

    Art.putValue(yPos_Id, std_msgs.Int32_Payload(value))
  }

  def logInfo(msg: String): Unit = {
    Art.logInfo(id, msg)
  }

  def logDebug(msg: String): Unit = {
    Art.logDebug(id, msg)
  }

  def logError(msg: String): Unit = {
    Art.logError(id, msg)
  }
}

@datatype class StepperController_Initialization_Api (
  val id: Art.BridgeId,
  val zCmd_Id : Art.PortId,
  val xCmd_Id : Art.PortId,
  val yCmd_Id : Art.PortId,
  val zPos_Id : Art.PortId,
  val xPos_Id : Art.PortId,
  val yPos_Id : Art.PortId) extends StepperController_Api

@datatype class StepperController_Operational_Api (
  val id: Art.BridgeId,
  val zCmd_Id : Art.PortId,
  val xCmd_Id : Art.PortId,
  val yCmd_Id : Art.PortId,
  val zPos_Id : Art.PortId,
  val xPos_Id : Art.PortId,
  val yPos_Id : Art.PortId) extends StepperController_Api {

  // Logika spec var representing port state for incoming event data port
  @spec var zCmd: Option[std_msgs.Int32] = $

  def get_zCmd() : Option[std_msgs.Int32] = {
    Contract(
      Ensures(
        Res == zCmd
      )
    )
    val value : Option[std_msgs.Int32] = Art.getValue(zCmd_Id) match {
      case Some(std_msgs.Int32_Payload(v)) => Some(v)
      case Some(v) =>
        Art.logError(id, s"Unexpected payload on port zCmd.  Expecting 'std_msgs.Int32_Payload' but received ${v}")
        None[std_msgs.Int32]()
      case _ => None[std_msgs.Int32]()
    }
    return value
  }

  // Logika spec var representing port state for incoming event data port
  @spec var xCmd: Option[std_msgs.Int32] = $

  def get_xCmd() : Option[std_msgs.Int32] = {
    Contract(
      Ensures(
        Res == xCmd
      )
    )
    val value : Option[std_msgs.Int32] = Art.getValue(xCmd_Id) match {
      case Some(std_msgs.Int32_Payload(v)) => Some(v)
      case Some(v) =>
        Art.logError(id, s"Unexpected payload on port xCmd.  Expecting 'std_msgs.Int32_Payload' but received ${v}")
        None[std_msgs.Int32]()
      case _ => None[std_msgs.Int32]()
    }
    return value
  }

  // Logika spec var representing port state for incoming event data port
  @spec var yCmd: Option[std_msgs.Int32] = $

  def get_yCmd() : Option[std_msgs.Int32] = {
    Contract(
      Ensures(
        Res == yCmd
      )
    )
    val value : Option[std_msgs.Int32] = Art.getValue(yCmd_Id) match {
      case Some(std_msgs.Int32_Payload(v)) => Some(v)
      case Some(v) =>
        Art.logError(id, s"Unexpected payload on port yCmd.  Expecting 'std_msgs.Int32_Payload' but received ${v}")
        None[std_msgs.Int32]()
      case _ => None[std_msgs.Int32]()
    }
    return value
  }
}
