#include "seed_imaging_microros_pkg/user_headers/esp32_stepper_src.h"

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

static esp32_stepper_base_t node;

int main(int argc, char ** argv)
{
    (void)argc;
    (void)argv;

    // A failure here means the node could not create the entities it needs, so
    // spinning would busy-wait forever on a node that can never publish or
    // receive.  Exiting non-zero instead lets the launching layer notice.
    rcl_ret_t init_status = esp32_stepper_base_init(&node);
    if (init_status != RCL_RET_OK) {
        LOG_ERROR("esp32_stepper initialization failed with status %d; aborting", (int) init_status);
        return 1;
    }

    // Invoke initialize entry point
    esp32_stepper_initialize(&node);

    LOG_INFO("esp32_stepper infrastructure set up");

    esp32_stepper_base_spin(&node);

    return 0;
}
