// #Sireum

package seedimaging

import org.sireum._
import art._
import art.PortMode._
import art.DispatchPropertyProtocol._
import art.Art.BridgeId._
import art.Art.PortId._

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

object Arch {
  val SeedImagingSystem_Instance_jetson_scan : seedimaging.SeedImaging.ScanController_jetson_scan_Bridge = {
    val start = Port[std_msgs.Int32] (id = portId"0", name = "SeedImagingSystem_Instance_jetson_scan_start", mode = EventIn)
    val zCmd = Port[std_msgs.Int32] (id = portId"1", name = "SeedImagingSystem_Instance_jetson_scan_zCmd", mode = EventOut)
    val xCmd = Port[std_msgs.Int32] (id = portId"2", name = "SeedImagingSystem_Instance_jetson_scan_xCmd", mode = EventOut)
    val yCmd = Port[std_msgs.Int32] (id = portId"3", name = "SeedImagingSystem_Instance_jetson_scan_yCmd", mode = EventOut)
    val zPos = Port[std_msgs.Int32] (id = portId"4", name = "SeedImagingSystem_Instance_jetson_scan_zPos", mode = EventIn)
    val xPos = Port[std_msgs.Int32] (id = portId"5", name = "SeedImagingSystem_Instance_jetson_scan_xPos", mode = EventIn)
    val yPos = Port[std_msgs.Int32] (id = portId"6", name = "SeedImagingSystem_Instance_jetson_scan_yPos", mode = EventIn)

    seedimaging.SeedImaging.ScanController_jetson_scan_Bridge(
      id = bridgeId"0",
      name = "SeedImagingSystem_Instance_jetson_scan",
      dispatchProtocol = Sporadic(min = 1),
      dispatchTriggers = None(),

      start = start,
      zCmd = zCmd,
      xCmd = xCmd,
      yCmd = yCmd,
      zPos = zPos,
      xPos = xPos,
      yPos = yPos
    )
  }
  val SeedImagingSystem_Instance_esp32_stepper : seedimaging.SeedImaging.StepperController_esp32_stepper_Bridge = {
    val zCmd = Port[std_msgs.Int32] (id = portId"7", name = "SeedImagingSystem_Instance_esp32_stepper_zCmd", mode = EventIn)
    val xCmd = Port[std_msgs.Int32] (id = portId"8", name = "SeedImagingSystem_Instance_esp32_stepper_xCmd", mode = EventIn)
    val yCmd = Port[std_msgs.Int32] (id = portId"9", name = "SeedImagingSystem_Instance_esp32_stepper_yCmd", mode = EventIn)
    val zPos = Port[std_msgs.Int32] (id = portId"10", name = "SeedImagingSystem_Instance_esp32_stepper_zPos", mode = EventOut)
    val xPos = Port[std_msgs.Int32] (id = portId"11", name = "SeedImagingSystem_Instance_esp32_stepper_xPos", mode = EventOut)
    val yPos = Port[std_msgs.Int32] (id = portId"12", name = "SeedImagingSystem_Instance_esp32_stepper_yPos", mode = EventOut)

    seedimaging.SeedImaging.StepperController_esp32_stepper_Bridge(
      id = bridgeId"1",
      name = "SeedImagingSystem_Instance_esp32_stepper",
      dispatchProtocol = Sporadic(min = 1),
      dispatchTriggers = None(),

      zCmd = zCmd,
      xCmd = xCmd,
      yCmd = yCmd,
      zPos = zPos,
      xPos = xPos,
      yPos = yPos
    )
  }

  val ad : ArchitectureDescription = {

    ArchitectureDescription(
      components = IS[Art.BridgeId, Bridge] (SeedImagingSystem_Instance_jetson_scan, SeedImagingSystem_Instance_esp32_stepper),

      connections = IS[Art.ConnectionId, UConnection] (Connection(from = SeedImagingSystem_Instance_jetson_scan.zCmd, to = SeedImagingSystem_Instance_esp32_stepper.zCmd),
                                                       Connection(from = SeedImagingSystem_Instance_jetson_scan.xCmd, to = SeedImagingSystem_Instance_esp32_stepper.xCmd),
                                                       Connection(from = SeedImagingSystem_Instance_jetson_scan.yCmd, to = SeedImagingSystem_Instance_esp32_stepper.yCmd),
                                                       Connection(from = SeedImagingSystem_Instance_esp32_stepper.zPos, to = SeedImagingSystem_Instance_jetson_scan.zPos),
                                                       Connection(from = SeedImagingSystem_Instance_esp32_stepper.xPos, to = SeedImagingSystem_Instance_jetson_scan.xPos),
                                                       Connection(from = SeedImagingSystem_Instance_esp32_stepper.yPos, to = SeedImagingSystem_Instance_jetson_scan.yPos))
    )
  }
}
